### ISSUE TITLE
Library not loaded: /usr/local/lib/libffmpeg.dylib (OSX)

### ISSUE THREAD

**Issue by marcbeezy** [electron-userland/electron-prebuilt#104]
I have not used electron in a while, started a new project with `npm i --save-dev electron-prebuilt` and am receiving this error. I don't see anything in the [README.md](https://github.com/electron-userland/electron-prebuilt/blob/master/README.md) about installing anything special. I have pasted the error below for reference. Any help is greatly appreciated, I will continue to try and resolve this as well.

Thanks!

Process:               Electron [633]
Path:                  /usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron
Identifier:            Electron
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        node [632]
Responsible:           Terminal [621]
User ID:               501

Date/Time:             2016-03-11 22:22:11.129 -0800
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        20D3F0F9-F258-669F-C057-F75504E4FF80

Time Awake Since Boot: 250 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libffmpeg.dylib
  Referenced from: /usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found

Binary Images:
    0x7fff6ba45000 -     0x7fff6ba7c007  dyld (360.19) <9D05FDF4-65CE-3B53-86D4-ABE1A5BF35F3> /usr/lib/dyld
    0x7fff8a8b9000 -     0x7fff8aa87ffb  com.apple.QuartzCore (1.11 - 410.14) <CB19502B-D25F-379C-B50F-08A98FF73B68> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff8ecb6000 -     0x7fff8ecb7ffb  libSystem.B.dylib (1226.10.1) <5A4257EF-3145-3BB3-87A4-0D2404A9462D> /usr/lib/libSystem.B.dylib
    0x7fff8f644000 -     0x7fff90267ff7  com.apple.AppKit (6.9 - 1404.34) <467468E2-C551-3408-B351-414B21F57DEB> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff905e0000 -     0x7fff905eefff  com.apple.opengl (12.0.40 - 12.0.40) <D37D88AE-0731-3105-99AB-984DA9B9BCE6> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff912f9000 -     0x7fff9143efff  com.apple.QTKit (7.7.3 - 2943) <6DD72D38-9449-3289-904E-B6E148993AA5> /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
    0x7fff9b46b000 -     0x7fff9b4dffff  com.apple.framework.IOKit (2.0.2 - 1179.20.6) <D92E537D-F96D-39E1-B9AC-9A18943AFCC7> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff9bb72000 -     0x7fff9bbc5ff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff9d6b5000 -     0x7fff9d6b5fff  com.apple.Carbon (154 - 157) <34263101-328D-3FE4-B212-14BD3CFF6965> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon

**Comment by htmfilho** [comment]
The same happening here. :-(

**Comment by maxogden** [comment]
Here is the electron repository: http://github.com/atom/electron

**Comment by johnmuhl** [comment]
Known issue https://github.com/atom/electron/issues/4765

**Comment by ZakariaRidouh** [comment]
It's been fixed at atom/electron#4769
