### ISSUE TITLE
Install fails on my windows 7 machine, but works on others

### ISSUE THREAD

**Issue by lexluthor91** [electron-userland/electron-prebuilt#107]
I have been debugging this with my friends, trying to make it work on my PC, but we just couldn't go around it. Same method works on several other machines without problems, only my PC gives us trouble. Here is the error part of the log:
<pre>
7269 verbose stack Error: electron-prebuilt@0.33.9 postinstall: `node install.js`
7269 verbose stack Exit status 3221225501
7269 verbose stack     at EventEmitter.<anonymous> (C:\Users\LexLuthor\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
7269 verbose stack     at emitTwo (events.js:100:13)
7269 verbose stack     at EventEmitter.emit (events.js:185:7)
7269 verbose stack     at ChildProcess.<anonymous> (C:\Users\LexLuthor\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
7269 verbose stack     at emitTwo (events.js:100:13)
7269 verbose stack     at ChildProcess.emit (events.js:185:7)
7269 verbose stack     at maybeClose (internal/child_process.js:827:16)
7269 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
7270 verbose pkgid electron-prebuilt@0.33.9
7271 verbose cwd S:\trunk\src\CentralServer\OPM 1.0\EkspertskiAlat
7272 error Windows_NT 6.1.7600
7273 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\LexLuthor\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-prebuilt"
7274 error node v5.7.1
7275 error npm  v3.8.0
7276 error code ELIFECYCLE
7277 error electron-prebuilt@0.33.9 postinstall: `node install.js`
7277 error Exit status 3221225501
7278 error Failed at the electron-prebuilt@0.33.9 postinstall script 'node install.js'.
7278 error Make sure you have the latest version of node.js and npm installed.
7278 error If you do, this is most likely a problem with the electron-prebuilt package,
7278 error not with npm itself.
7278 error Tell the author that this fails on your system:
7278 error     node install.js
7278 error You can get information on how to open an issue for this project with:
7278 error     npm bugs electron-prebuilt
7278 error Or if that isn't available, you can get their info via:
7278 error     npm owner ls electron-prebuilt
7278 error There is likely additional logging output above.
7279 verbose exit [ 1, true ]
</pre>

**Comment by nelreina** [comment]
Does anyone have a answer for this issue???? 
@lexluthor91 How did you proceed ?

**Comment by lexluthor91** [comment]
@nelreina I did not proceed. I worked on my work PC. I am pretty sure a clean windows install would be a safe bet, because I believe this problem had something to do with previously installed software, but I could not go that route, because of ongoing stuff on my computer at the time.

Hope that was helpful!

**Comment by zeke** [comment]
@nelreina are you getting the same error? What version of Windows are you using?

**Comment by nelreina** [comment]
@lexluthor91 
The error is on my work pc windows 7 SP1. My personal computer is a Mac Book Pro (No problems)!  

@zeke 
Yes I am getting the same error (npm i electron-prebuilt) as of 2 day ago. But I found somewhat of a work around. I downloaded the prebuilt binaries put this is my project folder, and changed my start script to start from there.

**Comment by zeke** [comment]
>  I downloaded the prebuilt binaries put this is my project folder, and changed my start script to start from there.

@nelreina can you share that technique in more detail here? Might be useful for others.

**Comment by stanleyxu2005** [comment]
Remove corrupt files from  `c:\users\{name}\.electron` and download again.

**Comment by nelreina** [comment]
@zeke 
In the meantime at work we made use of the free update from Microsoft to win 10. so I do not have this issue anymore neither the example project :(. 


But my solution was to include electron-prebuild binary in your project folder and **NOT** make use of the global binary. 
### project - folder
projecy-name
- electron-prebuild
- ... 

### package.json
Use npm scripts to start electron. 
`npm run scripts` search for modules in your project folder first and then globally

package.json
```javascript
...
scripts:{
   // I don't remember exactly how I called it but if you google around you'll find it
   "start":"electron" // or "start":"electron-prebuild/electron"
}
...
```

run `npm start`

**Comment by zeke** [comment]
Thanks for the feedback, @stanleyxu2005 and @nelreina. Closing this out.
