### ISSUE TITLE
Linux/Docker: libnode.so: cannot open shared object file / Check failed: base::i18n::InitializeICU()

### ISSUE THREAD

**Issue by chromakode** [electron-userland/electron-prebuilt#109]
Running a local install inside a `node:4` docker image on Ubuntu Wily:

```
# ./node_modules/electron-prebuilt/dist/electron 
./node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory
```

If I set `LD_LIBRARY_PATH`, I get a stack trace:

```
# LD_LIBRARY_PATH=./node_modules/electron-prebuilt/dist/ ./node_modules/electron-prebuilt/dist/electron 
[1954:0318/011656:FATAL:content_main_runner.cc(711)] Check failed: base::i18n::InitializeICU(). 
#0 0x000001ae0c9e (/bel/node_modules/electron-prebuilt/dist/electron+0x1ae0c9d)
#1 0x000001af6e2b (/bel/node_modules/electron-prebuilt/dist/electron+0x1af6e2a)
#2 0x0000010aa198 (/bel/node_modules/electron-prebuilt/dist/electron+0x10aa197)
#3 0x0000010a939a (/bel/node_modules/electron-prebuilt/dist/electron+0x10a9399)
#4 0x000002ea79ec (/bel/node_modules/electron-prebuilt/dist/electron+0x2ea79eb)
#5 0x7f2dddfd9b45 __libc_start_main
#6 0x00000053a189 (/bel/node_modules/electron-prebuilt/dist/electron+0x53a188)

Aborted (core dumped)
```

Wasn't able to find much info on this from googling :( I tried running from inside the `dist` directory, no dice. An `strace` showed, interestingly, that it was trying to read from a path that appears to be truncated at the beginning:

```
open("/bel/node_modules/electron-prebuilt/dist/icudtl.dat", O_RDONLY) = -1 ENOENT (No such file or directory)
```

The correct path should be `/usr/src/app/bel/node_modules/electron-prebuilt/dist/icudtl.dat`. It seems to be cutting off at the beginning of the docker working directory, which is `/usr/src/app`.

```
# mount
...
overlayfs on /usr/src/app type overlayfs (rw,relatime,lowerdir=/mnt/shared-host,upperdir=/mnt/shared-local)
```

Perhaps a weird interaction with overlayfs? Or filesystem boundaries?

If I `npm install -g electron-prebuilt`, it works as expected. I seem to be able to run testron inside xvfb without issue.

I interpreted from the README that local installs were the standard way to go, but wasn't able to get it working out of box. Any ideas what may be amiss?

```
# uname -a
Linux b49f6e1ea9cc 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 GNU/Linux
```

**Comment by zeke** [comment]
Hi @chromakode. Not sure where to start with this issue. Are you still affected?
