### ISSUE TITLE
PDF.dll is not included in the windows package

### ISSUE THREAD

**Issue by uggrock** [electron-userland/electron-prebuilt#113]
pdf.dll is needed for printing jobs in windows, and currently it is not part of the prebuilt distribution.

**Comment by johnmuhl** [comment]
This should be reported to http://github.com/atom/electron. `electron-prebuilt` is not responsible for packaging.

**Comment by kevinsawicki** [comment]
I believe this issue can be closed now, this dll is no longer needed in current versions of Electron.

https://github.com/electron/electron/issues/6373
