### ISSUE TITLE
Add a command line arg to cli to detect development mode

### ISSUE THREAD

**Issue by parro-it** [electron-userland/electron-prebuilt#116]
I'm helping @sindresorhus with [electron-is-dev](https://github.com/sindresorhus/electron-is-dev), a lib to detect if an Electron app is running in production or development mode.

A first implementation of the lib check if the current process is started from a file containing `electron-prebuilt` in path:

``` js
module.exports = /[\\/]electron-prebuilt[\\/]/.test(process.execPath);
```

The idea is that an app is started with `electron .` while in development, and then, when packaged for production use, it is started using directly the Electron binaries.

But as we are discussing in [this issue](https://github.com/sindresorhus/electron-is-dev/issues/1), there are many tool app in the wild that are published on NPM  with `electron-prebuilt` as a dependency.
They usually start from a node cli, and then use `electron-prebuilt` to retrieve the path of Electron native executable and start that.

So, with the current check, these app will be detected  as development mode, even when they are not.
We think that the process could be improved by just adding a command argument in `cli.js` to allow our lib to detect that the app is started using `electron .` and not a custom cli.

Are you ok if we publish a PR to do this change? 
Do you have any suggestions or improvement to the method we thought?

**Comment by mafintosh** [comment]
If we were to add this I think setting an env in cli.js would be a less intrusive way to do it.

**Comment by parro-it** [comment]
Oh, yes it's a good idea, and as a bonus we can easily force it from command line or shell rc files.
What about `ELECTRON_ENV`? NODE_ENV seems an established convention...

**Comment by sindresorhus** [comment]
> What about ELECTRON_ENV?

👍

**Comment by parro-it** [comment]
@sindresorhus #118

**Comment by kevinsawicki** [comment]
Closing in favor of https://github.com/electron/electron/issues/7714, please subscribe to that issue for updates.
