### ISSUE TITLE
libnotify.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by SergioF1234** [electron-userland/electron-prebuilt#117]
If there is an existing Electron issue for this, please link it here:

https://github.com/atom/electron/issues

Describe your problem:
I am using Red Hat Enterprise Linux Server release 6.7 (Santiago);
Downloaded  atom.x86_64.rpm
As root I  executed:
 yum install atom.x86_64.rpm
then under my user id I  executed:
/usr/bin/atom and received:
/usr/share/atom/atom: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

What is the recommended solution?

**Comment by mafintosh** [comment]
You should open this on the electron repo instead (https://github.com/atom/electron)

**Comment by mafintosh** [comment]
This module is just for distributing the electron binary on npm
