### ISSUE TITLE
After Packing Into ASAR I am facing Issues With Path(Windows)

### ISSUE THREAD

**Issue by Hir06** [electron-userland/electron-prebuilt#119]
var win=path.join(__dirname,'config.EXE');
var exec = require('child_process').execFile;
exec(win);

this Is working Fine But After Packing it into ASAR .Exe is not getting Executed 
getting Error As Path Unspecified
Tried Without Path.join As Well but No Sucess
Can Anyone Faced The Same issue And Able to Resolve?

**Comment by chin2km** [comment]
Facing the same issue. Any help would be highly appreciated :)

**Comment by kevinsawicki** [comment]
Is the `config.exe` inside the `.asar` archive?

**Comment by Hir06** [comment]
that issue is resolved
we kept it inside archive then we unpacked that and it worked.

**Comment by kevinsawicki** [comment]
> that issue is resolved

Great to hear, closing this out 👍
