### ISSUE TITLE
The latest version v0.37.8 can't download. Only  I have this problem?

### ISSUE THREAD

**Issue by EasierChan** [electron-userland/electron-prebuilt#120]
The latest version v0.37.8 can't download. Only  I have this problem?

**Comment by TeodorKolev** [comment]
same

**Comment by suda** [comment]
It looks like only versions pushed to npm are:
```
versions:
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.2.0',
     '0.2.1',
     '0.3.0',
     '0.4.0',
     '0.4.1',
     '1.3.1',
     '1.3.2',
     '1.3.3' ]
```
(intercept from `npm view electron` command).

@zeke / @kevinsawicki is it possible to push missing versions too?

**Comment by zeke** [comment]
@suda we just started publishing under the name `electron` as of version `1.3.1`. Versions before that are actually an entirely different project. See https://github.com/electron-userland/electron-prebuilt/issues/160

To install a specific version of prebuilt:

```sh
npm i electron-prebuilt@0.37.8
```

To list all versions:

```sh
 npm show electron-prebuilt versions
```

**Comment by TeodorKolev** [comment]
fast response

**Comment by zeke** [comment]
@EasierChan did `electron-prebuilt` solve the problem for you?

**Comment by kevinsawicki** [comment]
Closing this out.
