### ISSUE TITLE
退出了demo后.右上角的图标还存在.点击remove就报错

### ISSUE THREAD

**Issue by lifetin** [electron-userland/electron-prebuilt#128]
退出了demo后.右上角的图标还存在.点击remove就报错 如图
另外说下,啥时出来翻译版的中文档呀?

![image](https://cloud.githubusercontent.com/assets/10474968/15271579/4f1ffcaa-1a83-11e6-8dca-85325938ac1c.png)

**Comment by anr09** [comment]
你写中文在这里人家看得懂吗？

**Comment by kevinsawicki** [comment]
I believe this is the same issue as https://github.com/electron/electron-api-demos/issues/189 which has been fixed and released, closing this out.
