### ISSUE TITLE
Prevent window from closing on Cmd + W

### ISSUE THREAD

**Issue by parisk** [electron-userland/electron-prebuilt#129]
Hi, I am building a desktop app with Electron and I am using `electron-prebuit` in development.

My issue is that I would like to use the <kbd>⌘</kbd> + <kbd>W</kbd> shortcut (on my Mac), but no matter if I bind it or not (preventing default and stopping propagation as well) Electron will close the window.

This does not happen in the built version of my app though. Happens only with Electron pre-built.

**Comment by johnmuhl** [comment]
That behavior is part of the Electron `default_app` and should be reported to [electron/electron](/electron/electron) if want it changed.
