### ISSUE TITLE
Is there a way to specify a past version of electron?

### ISSUE THREAD

**Issue by monfera** [electron-userland/electron-prebuilt#132]
In case some dependency fails with the current version but passes with an old one, e.g.

https://github.com/hokein/electron-sample-apps/issues/29

**Comment by mafintosh** [comment]
you can use the `@` syntax with npm. `npm install electron-prebuilt@0.36.0` fx

**Comment by monfera** [comment]
Thank you, indeed it picked up the respective prebuilt version!
