### ISSUE TITLE
1.1.0 or 1.0.1?

### ISSUE THREAD

**Issue by nasht00** [electron-userland/electron-prebuilt#133]
I am confused.

Using electron-prebuilt 1.0.1 installs electron 1.1.0. 

The latest release of electron is 1.0.1 (http://electron.atom.io/), what's 1.1.0 ?

The end result when I try to start my electron app, I get:

```
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/electron/electron/tree/v1.1.0/docs

Error: Cannot find module 'app'
```

**Comment by mafintosh** [comment]
How are you installing 1.0.1? Latest version of electron is 1.1.0 according to the repo, https://github.com/electron/electron

**Comment by nasht00** [comment]
My package.json has this:

```
  "devDependencies": {
    "electron-packager": "latest",
    "electron-prebuilt": "^1.0.1"
  }
```

Sorry, I should have used ` "electron-prebuilt": "1.0.1"`. My bad.

Regarding 1.1.0, you are correct on github it is released, but on the official electron website they still display 1.0.1. Maybe it's not officially released yet...

**Comment by mafintosh** [comment]
we track the one on github since that is easy to automate
