### ISSUE TITLE
Relative require calls dont work?

### ISSUE THREAD

**Issue by aleclarson** [electron-userland/electron-prebuilt#136]
```sh
cd /path/to/parent/of/my-module
devtool
```

```js
require('./my-module') // => Throws the error: Cannot find module './my-module'

require(process.cwd() + '/my-module') // => Works as expected.
```

Any thoughts?

**Comment by nihakue** [comment]
Having a simillar issue.

```
.
├── assets
│   ├── clefs.png
│   ├── free_bar.png
│   └── note.png
├── dist
│   ├── Notes.js
│   └── app.js
├── index.html
├── index.js
├── node_modules
├── package.json
└── src
    ├── css
    └── js
```

inside of app.js:

```
const {Note} = require('./Notes.js');  // => Throws the error: Cannot find module './my-module'
const {Note} = require('./src/js/Notes.js') // => works.
```

**Comment by kevinsawicki** [comment]
Can you provide a small app that reproduces this behavior?

Can you log out `__dirname`  before your failed require calls? That should be the path that relative requires are resolved against.

**Comment by aleclarson** [comment]
Sorry, just realized this issue has nothing to do with Electron, per se.

I was attempting to `require('./my-module')` from the Developer Tools console that [jam3/devtool](https://github.com/jam3/devtool) provides. Since there is no `__dirname` in the console, the relative `require` fails.

Cheers 🍻
