### ISSUE TITLE
Can we speed up the updates of the new releases using npm?

### ISSUE THREAD

**Issue by lipis** [electron-userland/electron-prebuilt#138]
While I can see that this project is being updated almost instantly.. the npm package is always behind. (https://github.com/electron-userland/electron-prebuilt/commits/master)

**Comment by johnmuhl** [comment]
@lipis The intention is to update npm immediately but it seems like the Heroku app which does this is having a hard time connecting to npm for the last few releases. @maxogden could you add any relevant logs to electron-userland/electron-prebuilt-updater/issues/10 and I'll try my best to make time to investigate improving this in the next week.

**Comment by lipis** [comment]
Awesome! Looking forward to it..

**Comment by kevinsawicki** [comment]
The electron-prebuilt-updater is going to move to upgraded dynos going forward for future releases so hopefully there won't be anymore issues when the release service hook gets delivered to a sleeping hobby dyno that doesn't reply quick enough.

I'll be monitoring this closely for the next couple releases to ensure it immediately gets `npm` published as both `electron-prebuilt` and `electron`. Refs #160

@johnmuhl I'll post any logs I find if we do hit failures but I think this can be closed for now.
