### ISSUE TITLE
AngularJS request GET, ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by jechazelle** [electron-userland/electron-prebuilt#141]
Hi,

I try to develop an application with electron and angularjs, with GET request.

I build my APP to the MASS, I generate a file .app

When I launch my app and my get request (http://mywebsite.com/myfile.txt), I have an error ERR_NAME_NOT_RESOLVED.

How can I rmeove this error and remote my file please ?

**Comment by cameron-white-janrain** [comment]
I am experiencing the same problem.

![screen shot 2016-06-08 at 10 59 09 am](https://cloud.githubusercontent.com/assets/16297132/15905097/6b945622-2d68-11e6-8ece-89ed221158e4.png)

**Comment by jechazelle** [comment]
@cameron-white-janrain I used  "electron-builder": "3.27.0", "electron-prebuilt": "0.36.12", to build my pkg.

I resolved my problem to include 

```
<key>com.apple.security.network.client</key>
<true/>
```

in my default_mas_entitlements

https://github.com/electron-userland/electron-builder/issues/436#issuecomment-222546271

**Comment by kevinsawicki** [comment]
> You must include
> <key>com.apple.security.network.client</key>
> <true/>
> in my default_mas_entitlements

Thanks for mentioning this, adding these to the electron docs in https://github.com/electron/electron/pull/7162

Closing this out here.
