### ISSUE TITLE
DNSServiceRef is not initialized using v1.2.0 with mdns

### ISSUE THREAD

**Issue by cheshire137** [electron-userland/electron-prebuilt#144]
I originally filed https://github.com/agnat/node_mdns/issues/167 but was able to fix the problem by rolling back the version of electron-prebuilt I was using. Basically, when I use `"electron-prebuilt": "1.2.0"` with `"mdns": "^2.3.3"` and call `require('mdns')` in my Electron app, I get this error:

> Unexpected result while probing for avahi: TypeError: argument 4 must be a string (name)(…)

> node_modules/mdns/lib/avahi.js:28 Uncaught Error: DNSServiceRef is not initialized

This is with node 6.2.0:

```
% npm version
{ huxleyfm: '0.0.1',
  npm: '3.9.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.47',
  zlib: '1.2.8' }
```

If I switch to `"electron-prebuilt": "1.1.3"`, no such "DNSServiceRef is not initialized" error occurs. So there's something different between electron-prebuilt 1.2.0 and 1.1.3 that prevents mdns from working. Something to do with the bundled node maybe? I'm in OS X El Capitan.

**Comment by kevinsawicki** [comment]
@cheshire137 Have you tried Electron 1.3.x to see if it works there? If it doesn't, would you mind moving this issue over to https://github.com/electron/electron ? Thanks.

**Comment by kevinsawicki** [comment]
@cheshire137 any updates?

**Comment by cheshire137** [comment]
Sorry for the delay! I haven't tried this again, I think because my needs for the app I was building changed such that I didn't need mdns. I'm cool with closing this issue. 👍

**Comment by kevinsawicki** [comment]
>  I'm cool with closing this issue. 👍

Okay, closing this out here, for anyone visiting here and having similar issues, please raise a new issue on https://github.com/electron/electron/issues for it, thanks.
