### ISSUE TITLE
Failed at the nwjs@1.4.2 postinstall script 'node postinstall.js'

### ISSUE THREAD

**Issue by sentsin** [electron-userland/electron-prebuilt#145]
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nwjs" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! nwjs@1.4.2 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nwjs@1.4.2 postinstall script 'node postinstall.js'.
npm ERR! This is most likely a problem with the nwjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nwjs
npm ERR! There is likely additional logging output above.

System：Mac OS X EI Capitan 10.11.5

**Comment by changran52m** [comment]
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.3.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@1.3.3 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/changran/Dropbox/Document/ehands/npm-debug.log
```

**Comment by kevinsawicki** [comment]
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nwjs" "-g"

I think you may have reported this to the wrong repository, it looks like you were installing [nwjs](http://nwjs.io/) and not electron. If you are having issues installing nwjs, you should report it to https://github.com/nwjs/nw.js/issues

Electron can be installed by running:

```
npm install electron
```

Closing this out.
