### ISSUE TITLE
Uncaught Error: spawn path-to-exe ENOENT

### ISSUE THREAD

**Issue by puranjayjain** [electron-userland/electron-prebuilt#146]
**Note** not an electron issue but opened an issue on the module: https://github.com/fent/node-youtube-dl/issues/107
Describe your problem:
The problem is that the node-youtube-dl throws the following error when executed:
```
Uncaught Error: spawn path-to-youtube-dl.exe ENOENT
```
Moreover, the code executes perfectly in the devtools console.

On investigation it was revealed that child_process.spawn and exec wont work but execFile would, so I sifted through the code and found that it uses execFile only:
https://github.com/fent/node-youtube-dl/blob/master/lib/youtube-dl.js#L161

I'm using the following:
Node: v6.1.0 (via nodist)
OS: Windows 10 (x64) Enterprise
Electron: v1.2.0

**Comment by kevinsawicki** [comment]
Can you include a snippet of code that reproduces the issue? Thanks.

Also, is this happening with your packaged app or when running the development version of it?

**Comment by puranjayjain** [comment]
It happens so that the issue seems to be resolved with the newer node versions and a little workaround. Thank you for your help. I'll reopen this issue if that changes
