### ISSUE TITLE
Error: connect ETIMEDOUT 192.30.252.131:443

### ISSUE THREAD

**Issue by qamarm** [electron-userland/electron-prebuilt#148]
If there is an existing Electron issue for this, please link it here:

https://github.com/atom/electron/issues

Describe your problem:
I am trying to install electron-prebuilt, and I am behind a corporate proxy.
I get the error below. Any idea why install.js is trying to connect to github.com (192.30.252.131)?

$ npm install electron-prebuilt

> electron-prebuilt@1.2.1 postinstall /home/xxxxxx/node_modules/electron-prebuilt
> node install.js

Downloading electron-v1.2.1-linux-x64.zip
Error: connect ETIMEDOUT 192.30.252.131:443
/home/xxxxxx/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: connect ETIMEDOUT 192.30.252.131:443
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
npm WARN ENOENT ENOENT: no such file or directory, open '/home/xxxxxx/package.json'
npm WARN EPACKAGEJSON /home/xxxxxx No description
npm WARN EPACKAGEJSON /home/xxxxxx No repository field.
npm WARN EPACKAGEJSON /home/xxxxxx No README data
npm WARN EPACKAGEJSON /home/xxxxxx No license field.
npm ERR! Linux 2.6.32-573.22.1.el6.x86_64
npm ERR! argv "/home/xxxxxx/tools/node-v5.0.0-linux-x64/bin/node" "/home/xxxxxx/tools/node-v5.0.0-linux-x64/bin/npm" "install" "electron-prebuilt"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.2.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@1.2.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxxxxx/npm-debug.log

**Comment by qamarm** [comment]
RESOLVED.
electron-download defaults to github to download electron-v1.2.1-linux-x64.zip.
I downloaded electron-v1.2.1-linux-x64.zip and published to an internal artifactory repository. I then set the ELECTRON_MIRROR env variable to the location of the internal repository.

**Comment by kevinsawicki** [comment]
> RESOLVED.

👍 Glad to hear it, closing this out.
