### ISSUE TITLE
Webframe error.

### ISSUE THREAD

**Issue by ahgan84** [electron-userland/electron-prebuilt#152]
Hi guys, I encounter error when trying to use a zoom in function from webframe. Is the below code correct?

`const electron = require('electron');
const {app} = electron;
const {BrowserWindow} = electron;
let win;
var settings = require('./settings');
const {ipcMain} = require('electron');
const {webFrame} = require('electron');
webFrame.setZoomFactor(2);`

The error is :
`Cannot read property 'setZoomFactor' of undefined`.

I call the function at the top of the page. Is it correct?

**Comment by ahgan84** [comment]
I use another approach and it worked. I put in web-preference.

`win = new BrowserWindow({ fullscreen: true, webPreferences: { zoomFactor: 2 }`

**Comment by kevinsawicki** [comment]
`webFrame.setZoomFactor` can only be called from the renderer process, not the main process where you are creating the `BrowserWindow`.

http://electron.atom.io/docs/api/web-frame/

So I believe this can be closed.
