### ISSUE TITLE
npm errors while installing electron-prebuilt package

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [electron-userland/electron-prebuilt#153]
A askubuntu.com user uses Ubuntu 16.04LTS dual-booted with Windows 10 on his ASUS X552EA laptop running on AMD processors. He has been trying to install some packages on his system with npm. The command he used was a simple:

    npm install

after changing to the directory of his package. He get a few warnings and a lot of errors:

![http://i.stack.imgur.com/3zmY5.png](http://i.stack.imgur.com/3zmY5.png)

Could someone helps him on askubuntu.com or on this issue to understand and fix this problem?

> askubuntu.com question: http://askubuntu.com/questions/786061/npm-errors-while-installing/786094

**Comment by imdpm** [comment]
Electron-prebuild absent; wasn't installed perhaps.

**Comment by imdpm** [comment]
This is the npm-debug.log file.

[https://drive.google.com/open?id=0Bym2yhq7uAlLNUtlOE5HWnJIX1k](url)

**Comment by imdpm** [comment]
When I tried to install electron-prebuilt using,

sudo npm install electron-prebuilt

it failed at electron electron.js

The message said, sh: 1: electron: not found

**Comment by rdpascua** [comment]
I got this very same error, It cannot install it with `npm install electron-prebuilt` --save-dev

**Comment by SuriyaaKudoIsc** [comment]
@imdpm @rdpascua 

Try **`npm install electron`** or with administrator rights  **`sudo npm install electron`**!

**Comment by SuriyaaKudoIsc** [comment]
...and then:

    sudo npm install electron-prebuilt

**Comment by rdpascua** [comment]
@SuriyaaKudoIsc I was able to fix my issue by removing the `~/.electron` folder, it turns out I have corrupted/incomplete download.

**Comment by imdpm** [comment]
I just installed electron, and the pomodoro installation went well, still some problem are there but they're not related I guess. I wonder though if there has to be a global installation, because I ran into same electron related problem with another package.

![screencat](https://cloud.githubusercontent.com/assets/16536094/16304811/b5b201b0-3974-11e6-91ad-81ccea05b87b.png)

**Comment by SuriyaaKudoIsc** [comment]
@imdpm Uninstall NodeJS and npm and install it again.

**Comment by zeke** [comment]
To avoid having to install npm packages with `sudo`, set your user as the owner of the npm directories.

```sh
 sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
```

For more info, see https://docs.npmjs.com/getting-started/fixing-npm-permissions

Let me know if that helps!

**Comment by rodebiet** [comment]
Also have this problem with Ubuntu 16.04 LTS on 64-bit intel.

[npm-debug.log.txt](https://github.com/electron-userland/electron-prebuilt/files/368748/npm-debug.log.txt)

**Comment by nmihaica** [comment]
@rodebiet confirmed.
Nothing worked out except reinstalling nodejs and npm via `nvm`.
Workaround for `nvm: command not found`
Copy
```
export NVM_DIR=~/.nvm
source ~/.nvm/nvm.sh
```
in ~/.bash_profile .
