### ISSUE TITLE
how to install old version or rollback to old version of electron?

### ISSUE THREAD

**Issue by AlaaSelim** [electron-userland/electron-prebuilt#158]
If there is an existing Electron issue for this, please link it here:

https://github.com/atom/electron/issues

Describe your problem:
i have an app the that i build using electron long time ago, after updating electron globally it doesn't work anymore, how i can rollback to the old version or reinstall old version of electron?

**Comment by AlaaSelim** [comment]
never mind i found out how thanks

**Comment by jaron-l** [comment]
Just for those who find this:

`npm install electron@<version_number>`
