### ISSUE TITLE
The `electron` package name on npm

### ISSUE THREAD

**Issue by zeke** [electron-userland/electron-prebuilt#160]
The Electron team at GitHub recently reached out to @logicalparadox to see if he'd be willing to let us take over the [`electron` npm package](https://www.npmjs.com/package/electron). He has graciously agreed to do so, and has added our team as owners.

The motivation for the request was this:

> The electron installation process can often be a stumbling block for new users. There is an npm package called `electron-prebuilt` that most apps use to add electron to their development environment. Many users don't read the manual, though, and will often run `npm install electron` instead, only to discover (often after much confusion) that it's not the electron they're looking for.

So, now that we have the name, the goal is to make `npm install electron` feel just like `npm install electron-prebuilt`. How should we accomplish this?

### Option A: Pull off the Band-Aid™

 `npm deprecate` the `electron-prebuilt` package. The `deprecate` method allows you to specify a message that will be displayed to users when the package is installed. We could say something like: "As of version x.x.x, electron-prebuilt has been renamed to electron.". Change `name` to `electron` in the package.json file and begin publishing to npm as `electron`, but leave the repository name as-is.

### Option B: Tandem Releases for a While

Similar to option A, but with a longer window for users to make the switch. We would still deprecate `electron-prebuilt` on npm immediately, but instead of pulling the plug on the `electron-prebuilt` package right away, we could publish both packages in tandem for a while, then eventually stop publishing `electron-prebuilt` entirely.

### Option C: Side by Side, Forever

We could just leave `electron-prebuilt` as-is, and make `electron` a simple wrapper around it. Both packages would need to be [released automatically, as prebuilt is today](https://github.com/electron-userland/electron-prebuilt-updater).

I think the Electron team prefers **Option A** because it seems the simplest, but we are open to ideas. The end-goal is to make it easier for novices and pros alike to get electron running locally without confusion. The approach we should take is the one that minimizes confusion and maximizes developer happiness. :)

**Comment by mafintosh** [comment]
There are quite a few public projects that use electron-prebuilt as a dependency, https://www.npmjs.com/browse/depended/electron-prebuilt. 

It might be worth looking at those and seeing how many are affected by option A or B and potentially send PRs to upgrade their dependencies.

**Comment by zeke** [comment]
> send PRs to upgrade their dependencies

I pinged @greenkeeperio about PR automation tools, and @boennemann got back to me with what looks like the perfect thing: https://github.com/boennemann/github-change-remote-file

**Comment by zeke** [comment]
The Electron team just had a little pow-wow to figure out how to move forward. 
Here's the plan we came up with:

 :pencil2: Change the `name` field in package.json from `electron-prebuilt` to `electron`

:fork_and_knife: Fork the `electron-prebuilt-updater` repo into the `electron` org 

:satellite: Create a GitHub-owned Heroku instance to run the `electron-prebuilt-updater` service that listens for release webhooks.

:package: Refactor the updater app to automatically publish `electron-prebuilt` and `electron` in tandem. Two different names, same exact package. 

 :warning: `npm deprecate electron-prebuilt` in 90 days. This will give us a window to open PRs updating the dependency in popular open-source projects.

:ghost: Stop publishing `electron-prebuilt` entirely at the end of 2016

**Comment by englishextra** [comment]
@zeke Oh my God! My TODO.md is going to be quite a headache.

**Comment by zeke** [comment]
> My TODO.md is going to be quite a headache.

What do you mean? Hopefully we can automate the migration process for most users.

**Comment by englishextra** [comment]
@zeke Do I use `npm -g install electron` instead of `npm -g install electron-prebuilt` when using electron-packager to build windowed packages? Is that going to be redirected sort of at npm registry?

**Comment by zeke** [comment]
@englishextra per my comment above, our plan is to continue publishing the package under both names on npm through the end of 2016.

**Comment by englishextra** [comment]
@zeke I see, Option C—is my choice, and I had no confusion with what to install— electron or electron-prebuilt when I started building packages with electron-packager tool.

**Comment by develar** [comment]
electron-builder `5.23.0` will support `electron` npm package to detect electron version.

**Comment by zeke** [comment]
Awesome, @develar! Thanks for fixing, and for letting us know.

https://github.com/electron-userland/electron-builder/commit/aa0682f576549aa4ef0a6d64b6dbdb2206d862c8

**Comment by paulcbetts** [comment]
Hm, wonder what I'm gonna rename `electron-prebuilt-compile` to...

**Comment by englishextra** [comment]
assemble

**Comment by zeke** [comment]
This is a done deal!

Blog post: http://electron.atom.io/blog/2016/08/16/npm-install-electron
