### ISSUE TITLE
 Error: post install error, please remove node_modules          before retry

### ISSUE THREAD

**Issue by vipzrx** [electron-userland/electron-prebuilt#167]
If there is an existing Electron issue for this, please link it here:

https://github.com/atom/electron/issues

Describe your problem:

$ sudo cnpm install electron-prebuilt -g
[electron-prebuilt@1.2.8] link /usr/bin/electron@ -> ../lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt/cli.js
[electron-prebuilt@*] installed at node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt (152 packages, use 19s, speed 113.65kB/s, json 921.17kB, tarball 1.22MB)
excute post install scripts...
[electron-prebuilt@1.2.8] scripts.postinstall: "node install.js" at /usr/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt
/usr/lib/node_modules/.electron-prebuilt_npminstall/electron-prebuilt/1.2.8/electron-prebuilt/install.js:22
  throw err
  ^

Error: end of central directory record signature not found
    at /usr/lib/node_modules/.electron-prebuilt_npminstall/yauzl/2.4.1/yauzl/index.js:167:14
    at /usr/lib/node_modules/.electron-prebuilt_npminstall/yauzl/2.4.1/yauzl/index.js:473:5
    at /usr/lib/node_modules/.electron-prebuilt_npminstall/fd-slicer/1.0.1/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
Error: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/npminstall/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by zeke** [comment]
> Error: end of central directory record signature not found

This means the archive is corrupt. The best way to work around this would be to `rm -rf node_modules` and try again.
