### ISSUE TITLE
Install fails on windows 7 x64

### ISSUE THREAD

**Issue by hemanth7787** [electron-userland/electron-prebuilt#170]
Re-creating error:
Downloaded and installed https://nodejs.org/download/release/latest/node-v6.3.1-x64.msi
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install   -> Error happens here

Tried Console running with elevated privileges, also tried clearing "electron-quick-start/node_modules" folder

Log:
16035 verbose stack Error: electron-prebuilt@1.3.1 postinstall: `node install.js`
16035 verbose stack Exit status 3221225501
16035 verbose stack     at EventEmitter.<anonymous> (E:\Program files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
16035 verbose stack     at emitTwo (events.js:106:13)
16035 verbose stack     at EventEmitter.emit (events.js:191:7)
16035 verbose stack     at ChildProcess.<anonymous> (E:\Program files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
16035 verbose stack     at emitTwo (events.js:106:13)
16035 verbose stack     at ChildProcess.emit (events.js:191:7)
16035 verbose stack     at maybeClose (internal/child_process.js:852:16)
16035 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
16036 verbose pkgid electron-prebuilt@1.3.1
16037 verbose cwd E:\electron_wdir\electron-quick-start
16038 error Windows_NT 6.1.7600
16039 error argv "E:\Program files\nodejs\node.exe" "E:\Program files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
16040 error node v6.3.1
16041 error npm  v3.10.3
16042 error code ELIFECYCLE
16043 error electron-prebuilt@1.3.1 postinstall: `node install.js`
16043 error Exit status 3221225501
16044 error Failed at the electron-prebuilt@1.3.1 postinstall script 'node install.js'.
16044 error Make sure you have the latest version of node.js and npm installed.
16044 error If you do, this is most likely a problem with the electron-prebuilt package,
16044 error not with npm itself.
16044 error Tell the author that this fails on your system:
16044 error     node install.js
16044 error You can get information on how to open an issue for this project with:
16044 error     npm bugs electron-prebuilt
16044 error Or if that isn't available, you can get their info via:
16044 error     npm owner ls electron-prebuilt
16044 error There is likely additional logging output above.
16045 verbose exit [ 1, true ]

**Comment by hemanth7787** [comment]
One thing i noted is the step which downloads **electron_1.3.1_xx.zip**  is completing faster than it should be.

**Comment by hemanth7787** [comment]
I tried with 32-bit version of node https://nodejs.org/download/release/latest/node-v6.3.1-x86.msi
and the above error is not occurring there.

**Comment by carlosperate** [comment]
One of my users has reported also a similar issue for 1.3.1. I usually run the 32-bit version on my dev computer, but I'll see if I can replicate it later today.

**Comment by zeke** [comment]
@hemanth can you try running this on Node 4 LTS and see if it works?

**Comment by hemanth7787** [comment]
@zeke 
Same error while using Node 4.4.7 LTS x64
 https://nodejs.org/dist/v4.4.7/node-v4.4.7-x64.msi

-- error on command prompt -------

```
E:\electron_wdir\electron-quick-start>npm install
\
> electron-prebuilt@1.3.3 postinstall E:\electron_wdir\electron-quick-start\node
_modules\electron-prebuilt
> node install.js

Downloading electron-v1.3.3-win32-x64.zip
[>                                            ] 0.0% (0 B/s)
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.3.3 postinstall: `node install.js`
npm ERR! Exit status 3221225501
npm ERR!
npm ERR! Failed at the electron-prebuilt@1.3.3 postinstall script 'node install.
js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\electron_wdir\electron-quick-start\npm-debug.log
```

----Full error log --
https://dl.dropboxusercontent.com/u/92199994/logs/npm-debug.log

**Comment by hemanth7787** [comment]
No error while using Node 4.4.7 x86 
 https://nodejs.org/dist/v4.4.7/node-v4.4.7-x86.msi

**Comment by hemanth** [comment]
@zeke You ping the wrong Hemanth ;)

**Comment by zeke** [comment]
@hemanth now I know why I thought you changed your avatar. :)

**Comment by hemanth** [comment]
heh heh (:

**Comment by Aakash-Pray** [comment]
@hemanth 

I'm having the same issue and I have tried the solutions but don't get rid off this issue.

**Comment by hemanth7787** [comment]
@Aakash-Pray  please open an issue with detailed error logs.
