### ISSUE TITLE
npm install --save-dev electron-prebuilt. Error Downloading electron-v1.3.1-win32-x64.zip

### ISSUE THREAD

**Issue by robertolabarca** [electron-userland/electron-prebuilt#175]
This's my enviroment:
 

- npm repo is private (intranet)

- internet conection is with proxy

- no internet download permission (but i have electron-v1.3.1-win32-x64.zip file ) 

- Pc windows 10

I'm a noob , please Help Me

**Comment by robertolabarca** [comment]
- Download  electron-v1.3.1-win32-x64.zip to  C:\Users\<username>\.electron
- npm install electron-prebuilt -g

**Comment by dilipkumar2k6** [comment]
This worked for me as well. Thanks 👍
