### ISSUE TITLE
Fresh npm install with electron-prebuilt (1.3.1) results in npm warnings

### ISSUE THREAD

**Issue by monfera** [electron-userland/electron-prebuilt#176]
If there is an existing Electron issue for this, please link it here:

https://github.com/atom/electron/issues

Describe your problem:

Clean install yields a warning on `npm install`:

```
npm install
npm WARN unmet dependency XXXXX/node_modules/electron-prebuilt/node_modules/electron-download/node_modules/mkdirp requires minimist@'0.0.8' but will load
npm WARN unmet dependency XXXXX/node_modules/electron-prebuilt/node_modules/electron-download/node_modules/minimist,
npm WARN unmet dependency which is version 1.2.0
```

I don't have any related global installs or preexisting local installs, there's a single related line in `package.json`:
```
  "devDependencies": {
    "electron-prebuilt": "1.3.1"
  }
```

I haven't found a duplicate issue or anything in the `README` about it. Maybe a forgotten version number bump.

**Comment by zeke** [comment]
What OS are you on?

Can you `rm -rf node_modules && npm i` and report the results you see?

**Comment by monfera** [comment]
Thanks @zeke it's OS X. I didn't have a `node_modules` and it was before the initial commit. Unfortunately I no longer have that setup, because I switched to doing `npm install -g electron-prebuilt` instead of locally, and wrapping up things for today in Europe (night). My reason for switching to global wasn't mainly the above warning; I also decided not to tamper with `$PATH` and a global install took care of it (also, no warning there). Please close the issue.

**Comment by monfera** [comment]
@zeke I scrolled up and still had the console output, so I can confirm that the log was no more and no less than what I copied above, except that I replaced the actual path name with `XXXXX` above.

**Comment by zeke** [comment]
Thanks for responding @monfera. Glad you worked it out.
