### ISSUE TITLE
Module name conflict on TypeScript

### ISSUE THREAD

**Issue by rhysd** [electron-userland/electron-prebuilt#181]
I'm using TypeScript for Electron app and having a problem following the module name change from 'electron-prebuilt' to 'electron'.

I read [the blog post](http://electron.atom.io/blog/2016/08/16/npm-install-electron) and updated the type definition for TypeScript in DefinitelyTyped happily.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10665

Then I updated my project with new module but I noticed a problem.

There are two modules named 'electron'.
- Defined by Electron framework
- New 'electron' binary package

This is typically not a problem in JavaScript because there is no case where Electron app directly uses 'electron' package.

However, this is a problem for TypeScript.  TypeScript's type definition system doesn't assume such a naming conflict.  If `electron/index.d.ts` and `github-electron/index.d.ts` are in the same application, module name causes a conflict and compilation will fail.

If 'electron-prebuilt' package will be maintained as new 'electron' package, TypeScript user can continue to use 'electron-prebuilt' package to avoid this.
- Electron version: v1.3.3
- Operating system: OS X 10.11

**Comment by zeke** [comment]
Hey sorry for the late reply. Commented over at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10993
