### ISSUE TITLE
Path inside path.txt CI -> Box

### ISSUE THREAD

**Issue by oxala** [electron-userland/electron-prebuilt#183]
Hello guys,

I have an issue with the full path being stored inside `path.txt` by the `install.js` script.

In my setup npm modules being installed on the CI (Jenkins) and then the whole app being copied to the server boxes. And of course the path stored inside `path.txt` on Jenkins is different than those on the boxes.

Is there a way to work around that problem?

Or could we store relative path instead of the full one in `path.txt` (https://github.com/electron-userland/electron-prebuilt/blob/master/install.js#L44)?

Thanks.

**Comment by mafintosh** [comment]
It is already storing a relative path. Are you sure you are using a newer version?

**Comment by oxala** [comment]
Whoops. Sorry. I was too tired to realize that module that i use and that depends on `electron-prebuilt` has an old fixed version of electron-prebuilt in its package.json. Need to be more focused... I will close this accident issue.
