### ISSUE TITLE
ubuntu16.04

### ISSUE THREAD

**Issue by guzishiwo** [electron-userland/electron-prebuilt#184]
If you're having an issue _installing_ Electron, this is the place to report it.

If you're having an issue _using_ Electron, please report it at https://github.com/electron/electron/issues

* Electron version:
* Operating system:ubuntu16.04

**Comment by kevinsawicki** [comment]
Hi, what is the issue you are having?

**Comment by kevinsawicki** [comment]
Closing out for now, please comment with more information about your issue.
