### ISSUE TITLE
Geolocation Fails

### ISSUE THREAD

**Issue by m0n01i7h** [electron-userland/electron-prebuilt#185]
* Electron version: 1.3.3
* Operating system: Windows 10

Hi,
I have issue with resolving of geocoordinates
`navigator.geolocation.getCurrentPosition` returns with following error

```PositionError {code: 2, message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 403."}```

**Comment by johnmuhl** [comment]
`electron-prebuilt` is just the npm module. Issues with electron should be opened at [electron/electron](https://github.com/electron/electron).

**Comment by zeke** [comment]
@m0n01i7h see https://github.com/electron/electron/pull/7276
