### ISSUE TITLE
electron-prebuilt distribution size

### ISSUE THREAD

**Issue by cdaringe** [electron-userland/electron-prebuilt#187]
hey folks.

this isn't entirely contingent on -prebuilt, but i was expecting an empty electron package on osx to be ~40-50mb. instead, the prebuilt dist is ~120 mb.

if this is already documented, sorry for the dupe--i did search around first.  anyway, it's _huge_ enough where i'm convinced either is something is wrong in the packaging or we should make it super clear to consumers that the huge package is in fact _correct_.

any thoughts on the matter?

```sh
cdieringer@twires-MacBook-Pro:~/node/epkg/node_modules/electron-prebuilt/dist$ du -h .
...
117M
```

**Comment by Joshua-Smith** [comment]
That's what it has always been. When you compress it into an installer using electron-builder it ends up in the 40-50MB range you are expecting. (And only around 25MB for Windows with the new 7z compression option.)

**Comment by kevinsawicki** [comment]
Closing this out, that is the expected uncompressed size as @Joshua-Smith noted.

**Comment by cdaringe** [comment]
thanks dawgs! 🐶
