### ISSUE TITLE
Electron installation issue

### ISSUE THREAD

**Issue by jns4u** [electron-userland/electron-prebuilt#188]
My entire project is setup on linux distro. Previously it was working fine. Recently i moved entire file structure to disk mounted with widows file system now i am accessing project from there into linux. But after installing dependencies and running command $npm start into project root folder i am getting
Permission denied issue. below mentioned is the error details.

```
electron-quick-start@1.0.0 start /media/chanakya/B4CCD876CCD83478/Backup/KaliLinux/Projects/smdirNm/Node-UI/MobiMe_extremely_small
electron .
```

sh: 1: electron: Permission denied

npm ERR! Linux 4.0.0-kali1-686-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: electron .
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! This is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! electron .
npm ERR! You can get their info via:
npm ERR! npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

I appreciate any help in this regards.

Options i have tried:
1. Setting executable permission to installation folder.
2. Removing previously installed node modules and installing them again.

**Comment by kevinsawicki** [comment]
What are the permissions currently set on the `electron` executable?

**Comment by jns4u** [comment]
0777

**Comment by Ghwomb** [comment]
When I do `npm install electron --save-dev` on Ubuntu-Mate 16.04 I get similar errors.

Both node.js and npm is installed without any problems using `sudo aptitude install npm nodejs`. So both are available on the system. 

Node.js is located in `/usr/bin/nodejs` and can be executed. So it is not a matter of a bad symlink.

npm-debug.log attached as requested following a support request: [npm-debug.log.zip](https://github.com/electron-userland/electron-prebuilt/files/473517/npm-debug.log.zip).

**Comment by zeke** [comment]
@jns4u try doing a fresh install of your dependencies:

```sh
rm -rf node_modules && npm install
```

**Comment by jns4u** [comment]
sorry for late comment, fresh installation workout, removed all old branches and stages
