### ISSUE TITLE
Pin the version of `electron-download`

### ISSUE THREAD

**Issue by kgryte** [electron-userland/electron-prebuilt#190]
Pin the version of `electron-download` to `2.1.2` until electron-userland/electron-download#28 is resolved. The recent conversion of `electron-download` to ES6 without providing backfill support is causing install sequences to break for earlier Node.js environments not supporting ES6.

**Comment by kevinsawicki** [comment]
I was unable to unpublish `2.2.0` since it was >24 hours old, but I published `2.2.1` that is the exact same code as `2.1.2` so that should unbreak old node versions.

**Comment by kgryte** [comment]
@kevinsawicki Thanks!

**Comment by kevinsawicki** [comment]
I'm going to close this out since node 0.10/0.12 support has been restored in `electron-download` so pinning should no longer be needed.
