### ISSUE TITLE
Can't run electron with an application that uses pty.js

### ISSUE THREAD

**Issue by XDecs** [electron-userland/electron-prebuilt#194]
Hi,
I'm building an application using **xterm.js** and when I try to run it using electron I'm having an error with the **pty.js module**.

I've been fighting with this for about 3 days in a row and it's really frustrating... I tried with different npm modules to use web-terminals but all of them fail because they depend on pty.js module to work.

This is the error:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/PROJECT_PATH/node_modules/pty.js/lib/pty.js:9:11)

* Electron version: 1.4.1
* Operating system: debian 8.5 64bits
* npm version: 2.15.9
* node version: 4.5.0
* pty.js version: 0.3.1

**Comment by zeke** [comment]
It looks like the `pty` module has a native C dependency, which means you'll have to compile it against Electron's headers instead of Node's. See https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md and  the https://github.com/electron-userland/electron-builder readme for more info on this topic.

**Comment by XDecs** [comment]
Thanks @zeke I already tried with the second way suggested in the first link (https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) but is not working.

Now I changed the OS and I'm using Mac Os X El Capitan to see if was a problem from my linux VM but I'm still getting the error.

For the record: I'm using xterm.js module to build a desktop application using electron.js

**Comment by XDecs** [comment]
@zeke I followed the first way suggested in the first link and it's working smoothly!

Thanks for all your help! I can finally work with this.
