### ISSUE TITLE
webKitSpeechRecognition throws error "network"

### ISSUE THREAD

**Issue by Kayparker** [electron-userland/electron-prebuilt#196]
I have an application packaged in electron which uses WebkitSpeechRecognition for voice recognition. I used to work great since last week however it started throwing an error "network" lately. It works good on Google Chrome but electron package can't.

**Comment by zeke** [comment]
@Kayparker I have a hunch this is the Google API key that's embedded into Electron hitting a rate limit. Can you open this issue on [electron/electron](https://github.com/electron/electron/issues/new) instead, and please share example code and the entire error message you're seeing.

I suspect that we'll need to expose a way to configure your own Google API key for use in speech recognition requests, like we did recently for geolocation. See https://github.com/electron/electron/pull/7276

**Comment by zeke** [comment]
@Kayparker if and when you do open a new issue on `electron/electron`, please link to this one from it or vice-versa so it will be easier for others to track. Thanks!

**Comment by zeke** [comment]
Related: 

https://github.com/electron/electron/issues/7306
https://github.com/electron/electron/pull/7276

**Comment by friksa** [comment]
+1
