### ISSUE TITLE
 error electron-prebuilt@1.4.2 postinstall: `node install.js`

### ISSUE THREAD

**Issue by WillisZhang** [electron-userland/electron-prebuilt#197]
60091 silly postinstall electron-prebuilt@1.4.2 /home/somebody/.npm/electron-prebuilt/1.4.2/package/electron-prebuilt-eed69990
60092 info lifecycle electron-prebuilt@1.4.2~postinstall: electron-prebuilt@1.4.2
60093 verbose lifecycle electron-prebuilt@1.4.2~postinstall: unsafe-perm in lifecycle true
60094 verbose lifecycle electron-prebuilt@1.4.2~postinstall: PATH: /media/somebody/data_ext41/installed_sw_root/node-v6.7.0-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/home/somebody/.npm/electron-prebuilt/1.4.2/package/node_modules/.bin:/media/somebody/data_ext41/installed_sw_root/node-v6.7.0-linux-x64/bin:/media/somebody/data_ext41/installed_sw_root/apache-maven-3.3.9/bin:/media/somebody/data_ext41/installed_sw_root/jdk1.8.0_66/bin:/media/somebody/data_ext41/installed_sw_root/node-v6.7.0-linux-x64/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
60095 verbose lifecycle electron-prebuilt@1.4.2~postinstall: CWD: /home/somebody/.npm/electron-prebuilt/1.4.2/package
60096 silly lifecycle electron-prebuilt@1.4.2~postinstall: Args: [ '-c', 'node install.js' ]
60097 silly lifecycle electron-prebuilt@1.4.2~postinstall: Returned: code: 1  signal: null
60098 info lifecycle electron-prebuilt@1.4.2~postinstall: Failed to exec postinstall script
60099 verbose stack Error: electron-prebuilt@1.4.2 postinstall: `node install.js`
60099 verbose stack Exit status 1
60099 verbose stack     at EventEmitter.<anonymous> (/media/somebody/data_ext41/installed_sw_root/node-v6.7.0-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
60099 verbose stack     at emitTwo (events.js:106:13)
60099 verbose stack     at EventEmitter.emit (events.js:191:7)
60099 verbose stack     at ChildProcess.<anonymous> (/media/somebody/data_ext41/installed_sw_root/node-v6.7.0-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
60099 verbose stack     at emitTwo (events.js:106:13)
60099 verbose stack     at ChildProcess.emit (events.js:191:7)
60099 verbose stack     at maybeClose (internal/child_process.js:877:16)
60099 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
60100 verbose pkgid electron-prebuilt@1.4.2
60101 verbose cwd /home/somebody/.npm/electron-prebuilt/1.4.2/package
60102 error Linux 4.4.0-38-generic
60103 error argv "/media/somebody/data_ext41/installed_sw_root/node-v6.7.0-linux-x64/bin/node" "/media/somebody/data_ext41/installed_sw_root/node-v6.7.0-linux-x64/bin/npm" "install"
60104 error node v6.7.0
60105 error npm  v3.10.3
60106 error code ELIFECYCLE
60107 error electron-prebuilt@1.4.2 postinstall: `node install.js`
60107 error Exit status 1
60108 error Failed at the electron-prebuilt@1.4.2 postinstall script 'node install.js'.
60108 error Make sure you have the latest version of node.js and npm installed.
60108 error If you do, this is most likely a problem with the electron-prebuilt package,
60108 error not with npm itself.

**Comment by zeke** [comment]
@WillisZhang try this and let us know if you're still having issues:

```sh
rm -rf node_modules
npm install electron
```

**Comment by mayfairman** [comment]
Hi Zeke, Im having the same issue as above, I have tried the above and the same behaviour is exibited.

Command issued:-
`sudo npm install electron`

Expected Behaivour:-
electron to be install sucessfully with no errors

What I have tried:-
From other reports I have tried installing with `-unsafe-perm` and `-unsafe-perm -allow-root` neither of which did anything.
I then did the above suggestion `rm -rf node_modules` and tried the normal installation and the above - still the same behaivor.

System:-
Intel Core i3
8Gb Ram
Ubuntu 16.04 LTS
Header 4.4.0-36-generic
node ver 4.2.6 (installed via apt)
npm ver 3.5.2 (installed via apt)

Experienced Behaivour:-
`12664 verbose lifecycle electron@1.4.3~postinstall: CWD: /home/peter/MagicMirror/node_modules/electron
12665 silly lifecycle electron@1.4.3~postinstall: Args: [ '-c', 'node install.js' ]
12666 info lifecycle electron@1.4.3~postinstall: Failed to exec postinstall script
12667 verbose unlock done using /home/peter/.npm/_locks/staging-4dd14ff3ea0aa4e9.lock for /home/peter/MagicMirror/node_modules/.staging
12668 silly rollbackFailedOptional Starting
12669 silly rollbackFailedOptional Finishing
12670 silly runTopLevelLifecycles Starting
12671 silly runTopLevelLifecycles Finishing
12672 silly install printInstalled
12673 verbose stack Error: electron@1.4.3 postinstall: `node install.js`
12673 verbose stack spawn ENOENT
12673 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
12673 verbose stack     at emitTwo (events.js:87:13)
12673 verbose stack     at ChildProcess.emit (events.js:172:7)
12673 verbose stack     at maybeClose (internal/child_process.js:821:16)
12673 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
12674 verbose pkgid electron@1.4.3
12675 verbose cwd /home/peter/MagicMirror
12676 error Linux 4.4.0-36-generic
12677 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron" "-unsafe-perm" "-allow-root"
12678 error node v4.2.6
12679 error npm  v3.5.2
12680 error file sh
12681 error code ELIFECYCLE
12682 error errno ENOENT
12683 error syscall spawn
12684 error electron@1.4.3 postinstall: `node install.js`
12684 error spawn ENOENT
12685 error Failed at the electron@1.4.3 postinstall script 'node install.js'.
12685 error Make sure you have the latest version of node.js and npm installed.
12685 error If you do, this is most likely a problem with the electron package,
12685 error not with npm itself.
12685 error Tell the author that this fails on your system:
12685 error     node install.js
12685 error You can get information on how to open an issue for this project with:
12685 error     npm bugs electron
12685 error Or if that isn't available, you can get their info via:
12685 error     npm owner ls electron
12685 error There is likely additional logging output above.
12686 verbose exit [ 1, true ]`

Thanks
Peter

**Comment by Narvey** [comment]
Congratulations, now you have broken my node install even more than it was before:

`/usr/share/npm/lib/npm.js:18`
`  var fs = gfs.gracefulify(require('fs'))`
`               ^`
`TypeError: gfs.gracefulify is not a function`
`    at /usr/share/npm/lib/npm.js:18:16`
`    at Object.<anonymous> (/usr/share/npm/lib/npm.js:485:3)`
`    at Module._compile (module.js:410:26)`
`    at Object.Module._extensions..js (module.js:417:10)`
`    at Module.load (module.js:344:32)`
`    at Function.Module._load (module.js:301:12)`
`    at Module.require (module.js:354:17)`
`    at require (internal/module.js:12:17)`
`    at /usr/share/npm/bin/npm-cli.js:26:13`
`    at Object.<anonymous> (/usr/share/npm/bin/npm-cli.js:76:3)`

Oh, and by the way, here is the debug log file that was spit out before I tried your VERY broken workaround that made me have to reinstall npm: [npm-debug.log.txt](https://github.com/electron-userland/electron-prebuilt/files/551829/npm-debug.log.txt)

**Comment by mafintosh** [comment]
@Narvey please be respectful in your replies. the other people is this thread were simply trying to help.

**Comment by zbynek** [comment]
Electron postinstall tries to run "node install.js" but node is not a valid executable name on (some?) linux boxes. Making a symlink `cd /usr/bin; ln -s nodejs node` worked for me.

**Comment by mafintosh** [comment]
Is there a package what just normalizes the node/nodejs bin stuff? I know npm does this for shebangs but only after post-install has been run. 

We could publish a package that just contains the following:

```
#!/usr/local/bin node
require(path.resolve(process.argv[2]))
```

If the module exposed that as a "bin" script it would be able to run scripts in a cross-platform way and we could just use it as a dep here then instead of relying on "node" being in the path.

**Comment by Narvey** [comment]
package in npm, or package in apt-get (or urpm, or snapcraft, or whatever package manager you like)?

I think there already exists an apt-get package, but that won't solve this problem (and, besides, it will conflict with the non-nodejs-related "node" package).

If you want to make an npm package (can we call these modules for clarity?) and list it as a dependency of electron, more power to you, but I am curious why you wouldn't just change the electron module.

**Comment by mafintosh** [comment]
I would make it a module yea. If you know a way of fixing it in here that'd be fine too

**Comment by jrimpo** [comment]
I have the same error on a windows 7 machine with node: v6.6.0 and npm v3.5.3.  Note that this machine also has Visual Studio 2015 installed.  Could this be due to the version of node I have installed?  I have changed where the npm cache is stored (having it in the user's folder was problematic due to the need for elevated rights - see https://github.com/npm/npm/issues/5542).  I do not have elevated rights on this machine.  However, I have previously tried to install from a cmd prompt with elevated rights, and that was not successful.  I'm open to suggestions.

248486 verbose stack Error: electron@1.4.5 postinstall: `node install.js`
248486 verbose stack Exit status 1
248486 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
248486 verbose stack     at emitTwo (events.js:106:13)
248486 verbose stack     at EventEmitter.emit (events.js:191:7)
248486 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
248486 verbose stack     at emitTwo (events.js:106:13)
248486 verbose stack     at ChildProcess.emit (events.js:191:7)
248486 verbose stack     at maybeClose (internal/child_process.js:877:16)
248486 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
248487 verbose pkgid electron@1.4.5
248488 verbose cwd C:\xxxxx\Main\CRFS.Electron
248489 error Windows_NT 6.1.7601
248490 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
248491 error node v6.6.0
248492 error npm  v3.5.3
248493 error code ELIFECYCLE
248494 error electron@1.4.5 postinstall: `node install.js`
248494 error Exit status 1
248495 error Failed at the electron@1.4.5 postinstall script 'node install.js'.
248495 error Make sure you have the latest version of node.js and npm installed.
248495 error If you do, this is most likely a problem with the electron package,
248495 error not with npm itself.
248495 error Tell the author that this fails on your system:
248495 error     node install.js
248495 error You can get information on how to open an issue for this project with:
248495 error     npm bugs electron
248495 error Or if that isn't available, you can get their info via:
248495 error     npm owner ls electron
248495 error There is likely additional logging output above.
248496 verbose exit [ 1, true ]

**Comment by vchouhan** [comment]
I'm getting the same error when I try to install electron-prebuilt or electron.

<img width="1120" alt="screen shot 2016-11-09 at 12 45 38 am" src="https://cloud.githubusercontent.com/assets/1222739/20128426/dfaa410e-a615-11e6-990b-087cf169f97c.png">

**Comment by mrmign** [comment]
My ENV : Node v7.0.0  electron 1.4.8
when the installing reached `node install.js`, nothing happens after waiting for 30min,  
I just stop it and manually download the latest release package from https://github.com/electron/electron/releases into ~/.electron. Then go to electron folder `/usr/local/lib/node_modules/electron` , and execute `node install.js`, after several minutes, it exit normally. For the moment, you can see the changes in` /usr/local/lib/node_modules/electron` folder, there are `dist`folder and a `path.txt` file. And now you can execute electron correctly.

I don't find the url which  electron will use to  download the package. 
Hope that will help you!

@vchouhan  From the picture you submit, you can download the `electron-v1.4.5-darwin-x64.zip` package and put it into `~/.electron` folder, and then go to `/usr/local/lib/node_modules/electron` , run `node install.js`.

**Comment by wamoyo** [comment]
I don't know if this worked for anyone else, but I accidentally waited for a solid minute, and it completed the install : ) Imagine that, patience.

**Comment by kevinsawicki** [comment]
> Is this postinstall script platform-specific? If so, this bug should be able to be fixed for good by changing "node install.js" to "nodejs install.js" in the Linux postinstall.

It is supposed to be.

npm version 3.7.0+ handles this better where the node executable that was used to spawn npm is also used to run scripts like postinstall.

Closing this out since using npm 3.7.0 or above on Linux should resolve the `node` vs. `nodejs` issues .

**Comment by Lw-d** [comment]
electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.4.13 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

/usr/local/lib/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: connect ECONNREFUSED 52.216.80.80:443
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.4.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/liwen/WebstormProjects/npm-debug.log




someone tell me why?

**Comment by zeke** [comment]
@Jame0527 see https://electron.atom.io/docs/faq/#why-am-i-having-trouble-installing-electron

**Comment by ananthananth** [comment]
What worked for me: Installed the "current release"(v8.5) version of Node.js - 32  bit. Only this download helped.
