### ISSUE TITLE
Error on install: Cannot find module 'boom'

### ISSUE THREAD

**Issue by bcomnes** [electron-userland/electron-prebuilt#20]
```
> electron-prebuilt@0.25.1 install /Users/bret/Documents/projects/friends/node_modules/electron-prebuilt
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/bret/Documents/projects/friends/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

I'll try to narrow this down in a bit.

**Comment by maxogden** [comment]
if you run it again it will probably work

**Comment by bcomnes** [comment]
Oh, ya forgot to mention that part.  Running again, everything works.

**Comment by bcomnes** [comment]
Should I close the issue?  Sounds like its an upstream issue in nom?

**Comment by mafintosh** [comment]
Let keep it open for now incase others have the same problem

**Comment by francoislaberge** [comment]
Are we going to get a fix for this? Installing twice is awkward from a build machine perspective. I guess it's doable ultimately

**Comment by francoislaberge** [comment]
I'm installing repeatedly and having this and it's not going away. I went back to 0.32.0. I'll try on 0.33.0 again.

**Comment by ngoldman** [comment]
@bcomnes @francoislaberge is this still happening for you on v0.36+? Hoping to close this issue.

**Comment by francoislaberge** [comment]
I'm stuck back 0.34.1 for our use case, so I can't say. I have not been having this issue, not sure if some fuzzy matching just pulled in a fix downstream. Short answer: it seems gone for me.

**Comment by bcomnes** [comment]
I don't think I've run into this for a long time.

**Comment by ngoldman** [comment]
Okay thanks, marking as resolved for now.

**Comment by billwritescode** [comment]
This is still happening on 1.4.12. Any hope for a fix?

**Comment by elia314** [comment]
Was this fixed? I have same issue.

**Comment by maxfriedmann** [comment]
Still occurs... With NPM4&NPM5, locally "run it again" works, but in an automated process this is such an annoying thing!!!
