### ISSUE TITLE
Electron-v1.4.3-linux-x64.zip install fails 

### ISSUE THREAD

**Issue by benj13260** [electron-userland/electron-prebuilt#201]
Hi,

I have the following problem when installing electron

* Electron version:
Electron-v1.4.3-linux-x64.zip
* Operating system:
Ubuntu - Linux 4.2.0-42-generic

-----------

sudo npm install -g electron
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.4.3 postinstall /usr/local/lib/node_modules/electron
> node install.js

Downloading electron-v1.4.3-linux-x64.zip
Error: read ECONNRESET
/usr/local/lib/node_modules/electron/install.js:22
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:563:26)
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "electron"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.3 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by zeke** [comment]
`ECONNRESET` suggests that this was a network error. Give it another try and you should be good.

Note: You should avoid using `sudo` with npm. See https://docs.npmjs.com/getting-started/fixing-npm-permissions
