### ISSUE TITLE
electron terminated with signal SIGTRAP in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so

### ISSUE THREAD

**Issue by aprakash1976** [electron-userland/electron-prebuilt#203]
When running electron Version 1.4.3 under ubuntu 16.04. It generates the following stacktrace. 
I am stuck with this issue for a long time, we are using electron for high IO type operation. Any help is appreciated. 
(gdb) bt full
#0  0x00007efda7d67a6b in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

No symbol table info available.
#1  0x00007efda7d67bdf in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

No symbol table info available.
#2  0x00007efda7d87fa8 in g_thread_new () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

No symbol table info available.
#3  0x00007efda7d62281 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0

No symbol table info available.
#4  0x00007efdab212038 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

No symbol table info available.
#5  0x00007efdab212946 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

No symbol table info available.
#6  0x00007efdab213375 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

No symbol table info available.
#7  0x00007efdab170dd3 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

No symbol table info available.
#8  0x00007efdab170f50 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

No symbol table info available.
#9  0x00007efdab20ce75 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

No symbol table info available.
#10 0x00007efdab20d9d5 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

No symbol table info available.
#11 0x00007efdab15d7eb in g_file_monitor_file () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

No symbol table info available.
#12 0x00007efd9ea1b1e5 in ?? () from /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5

No symbol table info available.
#13 0x00007efdaa073359 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#14 0x00007efdaa054df8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#15 0x00007efd9ea1d886 in ?? () from /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5

No symbol table info available.
#16 0x00007efdaa055149 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#17 0x00007efdaa0571b5 in g_object_new_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#18 0x00007efdaa057521 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#19 0x00007efd9ea1b876 in ibus_bus_new_async () from /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5

No symbol table info available.
#20 0x00007efd9ec7c2f4 in ?? () from /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so

No symbol table info available.
#21 0x00007efdaa07022d in g_type_class_ref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#22 0x00007efdaa056dad in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#23 0x00007efdaa057534 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#24 0x00007efd9ec7ce02 in ibus_im_context_new () from /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so

No symbol table info available.
#25 0x00007efdaba8be7e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

No symbol table info available.
#26 0x00007efdaba8c7d9 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#27 0x00007efdaba8ca15 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

No symbol table info available.
#28 0x00007efdaba33067 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

No symbol table info available.
#29 0x00007efdaa04ffa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#30 0x00007efdaa061afc in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#31 0x00007efdaa06ad5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#32 0x00007efdaa06b08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#33 0x00007efdabbc1b54 in gtk_widget_realize () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

No symbol table info available.
#34 0x00007efdabbc2e68 in gtk_widget_set_parent () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

No symbol table info available.
#35 0x00007efdab9f1a03 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0

No symbol table info available.
#36 0x00007efdaa0530a7 in g_cclosure_marshal_VOID__OBJECTv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#37 0x00007efdaa0501d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#38 0x00007efdaa06a9a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#39 0x00007efdaa06b08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

No symbol table info available.
#40 0x0000000001b167af in ?? ()

No symbol table info available.
#41 0x0000000001b15d4e in ?? ()

No symbol table info available.
#42 0x0000000001b102e9 in ?? ()

No symbol table info available.
#43 0x0000000001b1023b in ?? ()

No symbol table info available.
#44 0x000000000358f58b in brightray::BrowserMainParts::ToolkitInitialized() ()

No symbol table info available.
#45 0x00000000026eecd3 in ?? ()

No symbol table info available.
#46 0x00000000026efac8 in ?? ()

No symbol table info available.
#47 0x00000000026e8ee6 in ?? ()

No symbol table info available.
#48 0x0000000001212047 in ?? ()

No symbol table info available.
#49 0x0000000001210b20 in ?? ()

No symbol table info available.
#50 0x00000000034690a3 in main ()

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
