### ISSUE TITLE
why is the folder red ?

### ISSUE THREAD

**Issue by geeflaxx** [electron-userland/electron-prebuilt#204]
http://www.bilder-upload.eu/show.php?file=967e7b-1477258720.png
in my folder is the name red 
and i get a many errors, that they want to go in the folder "electron" and search something 
but i haven't any data in these folder what can i do ?
http://www.bilder-upload.eu/show.php?file=58e559-1477259579.png
- Electron version:latest
- Operating system:raspberry pi

**Comment by kevinsawicki** [comment]
> why is the folder red ?

Not sure but you should consult your terminal's documentation for how it colorizes the `ls` output.
It could be because the files are large or because they are compressed archives.

The error looks to be because the `libnss3` library is missing, can you try installing the `libnss3-dev` package?
