### ISSUE TITLE
electron@1.4.4 appears to be broken

### ISSUE THREAD

**Issue by inca** [electron-userland/electron-prebuilt#206]
Following the advice from deprecation note from `electron-prebuilt@1.4.4` I switched to `electron@1.4.4` — and now I get "path.txt no such file or directory" which obviously has popped up a number of times (#76, #85, #193, etc.), but isn't fixable by `rm -rf node_modules && npm i`. `electron-prebuilt@1.4.4` works for me, so I believe packages are in fact not identical.

**Comment by faebeee** [comment]
I have same/similar problem. But my errors searches the `path.txt` not in the node_modules but in the project root.
`ENOENT: no such file or directory, open '/Users/fabs/Work/_work/banner-suite/app/app/path.txt' `

Any ideas?

**Comment by inca** [comment]
Yep, same for me.

Just a wild thought it might be related to https://github.com/electron/electron/issues/3708

**Comment by faebeee** [comment]
@inca are you sure? I'm not getting the error when I try to start electron. I'm getting it when I write

`let electron = require('electron')`

in my render process. 
I'm bundling with browserify and transpile it with babelify.
When I run browserify with `builtins: false`I'm getting the `path.txt` error.
Without it, I'll get 
`fs.readFileSync is not a function`

**Comment by inca** [comment]
don't know what the question is :) I'm sure it has something to do with switching from `electron-prebuilt` to `electron` package (with aforementioned versions)

**Comment by dperetti** [comment]
Same here on a fresh install (v. 1.4.6)

**Comment by inca** [comment]
I'm pretty sure it is because of Browserify (at least in my case) being able to locate package `electron` in `node_modules`, despite the fact that it is supposed to leave all `require('electron')` untouched (I'm building with `--ignore-missing`).

Seems we need a better way to bundle stuff for Electron. Most frontend frameworks (React, Vue, etc, etc) rely heavily on build toolchains, and avoiding them isn't a nice option.

**Comment by faebeee** [comment]
Fixed my problem. The problem was that browserify overwrote the `require('electron')` code

Solved by adding ` .external('electron')` to the bundler


browserify('./app/App.js',
 {
        debug: true,
    })
        .external('electron')
        .transform(vueify)
        .transform(babelify)
        .on('error', gutil.log)
        .bundle()
        .pipe(fs.createWriteStream("./app/build/bundle.js"))

Hope this helps you

**Comment by inca** [comment]
Conclusion: issue related to browserify which incorrectly bundles `require('electron')` from `node_modules` instead of leaving it alone.

Solution: `browserify --external=electron --no-builtins --no-browser-field --insert-global-vars=\"global\" ...` or see above for programmatical solutions.

Thanks everyone!

**Comment by zeke** [comment]
Thanks for following up, @inca
