### ISSUE TITLE
Latest built fails.

### ISSUE THREAD

**Issue by arjunmenon** [electron-userland/electron-prebuilt#212]
```
~$ npm install electron --save-dev
-
> electron@1.4.6 postinstall /home/arjun/node_modules/electron
> node install.js

/home/arjun/node_modules/electron/install.js:22
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)
npm ERR! Linux 3.19.0-73-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron" "--save-dev"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.6 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/arjun/npm-debug.log


```

Unable to install.
Running on elementary os freya, 32 bit
NPM version 2.15.9

**Comment by cjbturin** [comment]
Unable to install on Windows 10 x64
node 7.1.0 ; npm 3.10.9

`> electron@1.4.6 postinstall C:\Users\qwerty\AppData\Roaming\npm\node_modules\electron
> node install.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (C:\Users\qwerty\AppData\Roaming\npm\node_modules\electron\node_modules\single-line-log\ind
ex.js:12:16)
    at process.<anonymous> (C:\Users\qwerty\AppData\Roaming\npm\node_modules\electron\node_modules\single-line-log\index.js
:17:29)
    at emitOne (events.js:101:20)
C:\Users\qwerty\AppData\Roaming\npm
+-- tslint@3.15.1
| +-- colors@1.1.2
| +-- diff@2.2.3
| +-- findup-sync@0.3.0
| | `-- glob@5.0.15
| +-- glob@7.1.1
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3
| | +-- minimatch@3.0.3
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | +-- once@1.4.0
| | `-- path-is-absolute@1.0.1
| +-- optimist@0.6.1
| | +-- minimist@0.0.10
| | `-- wordwrap@0.0.3
| +-- resolve@1.1.7
| `-- underscore.string@3.3.4
|   +-- sprintf-js@1.0.3
|   `-- util-deprecate@1.0.2
`-- typescript@2.0.9

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "-g" "typescript" "tslint" "electron"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.`

**Comment by gucong3000** [comment]
Unable to install on Windows 10 x64

```bash
npm i electron --save

> electron@1.4.6 postinstall E:\work\FELS\node_modules\electron
> node install.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (E:\work\FELS\node_modules\single-line-log\index.js:12:16)
    at process.<anonymous> (E:\work\FELS\node_modules\single-line-log\index.js:17:29)
    at emitOne (events.js:101:20)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "electron" "--save"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
```

**Comment by elParano** [comment]
please try to reinstall the nodejs, and use the version 6.9.1,
because i have the same issue when i try to install nightmarejs. the install failed always when it reach the electron@1.6.4

i use various methode, but the one that it work for me is to download the 6.9.1 and unisntall the 7.1.0 version of nodejs, i try it again.
and it's work :)

i may sure also to delete the .electron and the npm-cache folders

i hope this method work for you ;)

**Comment by dcdeiv** [comment]
In my case I don't get any error, however it just does nothing for hours until I quit exhausted by the waiting.

```bash
$ sudo npm i -g electron
> electron@1.4.7 postinstall /path/to/electron
> node install.js


```

Ubuntu 16.04
node v6.9.1
npm v4.0.2

it does the same if I try to install it locally `$ npm install --save-dev electron`

**Comment by gucong3000** [comment]
@dcdeiv happen to node 7.1.0

**Comment by vtomic85** [comment]
@elParano I had the same problem and your solution worked for me. I had version 7.1.0 (I think), uninstalled it, then installed 6.9.1 and then I was able to do npm install and to run the app.

**Comment by gucong3000** [comment]
>I had the same problem and your solution worked for me. I had version 7.1.0 (I think), uninstalled it, then installed 6.9.1 and then I was able to do npm install and to run the app.

The same as me.

**Comment by deksden** [comment]
I have same issue on latest macOS: 
> electron@1.4.8 postinstall /usr/local/lib/node_modules/electron
> node install.js 

After it installation hangs. 
Node was 7.1.0 and 6.9.1, npm 4.0.2

Same behavior for electron 1.4.10, 1.4.8,1.4.6.

The only solution was to install v1.4.5 that works ok.

**Comment by lambdakris** [comment]
I ran into the same issue while running node 7.1.0 on Windows 10, however, upgrading to node 7.2.0 allowed me to install electron successfully

**Comment by devcybiko** [comment]
I have used node 6.9.1, 7.1.0, and 7.2.0 and the install always hangs on (macOS)

<code>
> electron@1.4.10 postinstall /Users/rmd378/.nvm/versions/node/v7.2.0/lib/node_modules/electron
> node install.js

Downloading electron-v1.4.10-darwin-x64.zip
Error: connect ETIMEDOUT 192.30.253.112:443
</code>

**Comment by zeke** [comment]
`EAI_AGAIN`, `ECONNRESET`, and `ETIMEDOUT` are all indications of network timeouts, and not actual issues with the electron npm package. The best resolution is to try switching networks, or just wait a bit and try installing again.

**Comment by kevinsawicki** [comment]
>  The best resolution is to try switching networks, or just wait a bit and try installing again.

👍 Closing this out since these are networking errors that can/will occur due to local connectivity issues or when GitHub is having an availability issue.

You can also attempt to download Electron directly from https://github.com/electron/electron/releases if installing via `npm` is failing.
