### ISSUE TITLE
Error in the script of installation

### ISSUE THREAD

**Issue by 7sixer** [electron-userland/electron-prebuilt#215]
* Electron version: Last
* Operating system: OSx 

I try to install electron with npm and it returned me an error in the script of installation. I attach the log file.
[npm-debug.log.zip](https://github.com/electron-userland/electron-prebuilt/files/598645/npm-debug.log.zip)

**Comment by shytikov** [comment]
It seems to be same as #212

**Comment by kevinsawicki** [comment]
```
8296 verbose lifecycle electron@1.4.7~postinstall: CWD: /usr/local/lib/node_modules/electron
8297 silly lifecycle electron@1.4.7~postinstall: Args: [ '-c', 'node install.js' ]
8298 silly lifecycle electron@1.4.7~postinstall: Returned: code: 1  signal: null
8299 info lifecycle electron@1.4.7~postinstall: Failed to exec postinstall script
```

Looks like the log provided does not contain the standard error output, can you include that from the terminal?

Are you still experiencing this issue with 1.4.13?

**Comment by kevinsawicki** [comment]
Closing this out until more information is available.
