### ISSUE TITLE
installation error - electron

### ISSUE THREAD

**Issue by aaabhilash97** [electron-userland/electron-prebuilt#221]
* Electron version: electron@1.4.10
* Operating system: Ubuntu 16.04

/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.4.10 postinstall /usr/local/lib/node_modules/electron
> node install.js

/usr/local/lib/node_modules/electron/install.js:22
  throw err
  ^

Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "electron"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.10 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.10 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

Attaching npm-debug.log

`13686 verbose lifecycle electron@1.4.10~postinstall: CWD: /usr/local/lib/node_modules/electron
13687 silly lifecycle electron@1.4.10~postinstall: Args: [ '-c', 'node install.js' ]
13688 silly lifecycle electron@1.4.10~postinstall: Returned: code: 1  signal: null
13689 info lifecycle electron@1.4.10~postinstall: Failed to exec postinstall script
13690 verbose unlock done using /home/abhilash/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
13691 silly rollbackFailedOptional Starting
13692 silly rollbackFailedOptional Finishing
13693 silly runTopLevelLifecycles Finishing
13694 silly install printInstalled
13695 verbose stack Error: electron@1.4.10 postinstall: `node install.js`
13695 verbose stack Exit status 1
13695 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
13695 verbose stack     at emitTwo (events.js:106:13)
13695 verbose stack     at EventEmitter.emit (events.js:191:7)
13695 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13695 verbose stack     at emitTwo (events.js:106:13)
13695 verbose stack     at ChildProcess.emit (events.js:191:7)
13695 verbose stack     at maybeClose (internal/child_process.js:877:16)
13695 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13696 verbose pkgid electron@1.4.10
13697 verbose cwd /home/abhilash/electron-quick-start
13698 error Linux 4.4.0-51-generic
13699 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron" "-g"
13700 error node v6.9.1
13701 error npm  v3.10.8
13702 error code ELIFECYCLE
13703 error electron@1.4.10 postinstall: `node install.js`
13703 error Exit status 1
13704 error Failed at the electron@1.4.10 postinstall script 'node install.js'.
13704 error Make sure you have the latest version of node.js and npm installed.
13704 error If you do, this is most likely a problem with the electron package,
13704 error not with npm itself.
13704 error Tell the author that this fails on your system:
13704 error     node install.js
13704 error You can get information on how to open an issue for this project with:
13704 error     npm bugs electron
13704 error Or if that isn't available, you can get their info via:
13704 error     npm owner ls electron
13704 error There is likely additional logging output above.
13705 verbose exit [ 1, true ]`

**Comment by virink** [comment]
it's also for mac

**Comment by nandd** [comment]
same error on Windows 10

**Comment by zeke** [comment]
The `EAI_AGAIN` error is a DNS lookup timeout, so it was probably a temporary issue with your network.

Try running `npm install electron` again.

**Comment by bigZ-again** [comment]
![image](https://cloud.githubusercontent.com/assets/15630922/21453789/be8e361e-c94d-11e6-8e45-f329b3285a90.png)

**Comment by zeke** [comment]
@bigZ-again the `ECONNRESET` error indicates a network issue. The download was probably taking too long and timed out. Please remove electron from `node_modules`, then try installing again.

**Comment by kevinsawicki** [comment]
Closing this out since, see https://github.com/npm/npm/issues/7348 for more details.
