### ISSUE TITLE
Issue installing electron

### ISSUE THREAD

**Issue by louise-r-blue** [electron-userland/electron-prebuilt#222]
Hi Electron,

I am unable to install (npm) electron or electron-prebuilt either globally or locally. Hangs at `node install.js`. At this point I have tried to ctrl c then cd into node_modules and then continue the install. (I read this somewhere). I receive this error as in screenshot.
![image](https://cloud.githubusercontent.com/assets/15900463/21441939/b34b0758-c8ff-11e6-88c0-eb271474b4c4.png)

Help would be appreciated:/

* Electron version:1.4.13
* Operating system:Linux -x64
* Node: v6.9.2

**Comment by kevinsawicki** [comment]
>  Hangs at node install.js

This script downloads ~40MB so it can take some time.

Try deleting it from `node_modules` and letting it run again until it completes.

**Comment by kevinsawicki** [comment]
Closing this out, this will raise a better error via #224

**Comment by louise-r-blue** [comment]
Hi Kevin,

Thanks for replying and sorry about my late reply. I realize you have closed this issue but I still have the same issue. Uninstalled electron (globally) then installed again. Still hangs on `node install.js`
![screenshot_20170104_162335](https://cloud.githubusercontent.com/assets/15900463/21630884/35e4d790-d29a-11e6-8c8a-56c6da374ee5.png)

**Comment by louise-r-blue** [comment]
I have included some of debug log. Strangely shows I am using node v 5.11.0. I am fairly certain I upgraded late last year. Do you think this part of issue?
![screenshot_20170104_164720](https://cloud.githubusercontent.com/assets/15900463/21631205/82c1cd68-d29d-11e6-8578-ba0dcd3aa531.png)
