### ISSUE TITLE
Install fails on Windows 10

### ISSUE THREAD

**Issue by apokaliptis** [electron-userland/electron-prebuilt#232]
[2017-02-13T01_40_23_562Z-debug.zip](https://github.com/electron-userland/electron-prebuilt/files/769923/2017-02-13T01_40_23_562Z-debug.zip)

I've tried to install electron and it keeps hanging on install.js before failing. I even tried [this suggestion](https://github.com/electron-userland/electron-prebuilt/issues/69#issuecomment-164636460), and it still doesn't work.

PS C:\Program Files\nodejs\node_modules\electron> npm install
npm WARN deprecated standard-format@1.6.10: standard-format is deprecated in favor of a built-in autofixer in 'standard'
. Usage: standard --fix
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> spawn-sync@1.0.15 postinstall C:\Program > Files\nodejs\node_modules\electron\node_modules\spawn-sync
> node postinstall

> electron@1.4.15 postinstall C:\Program Files\nodejs\node_modules\electron
> node install.js

C:\Program Files\nodejs\node_modules\electron\install.js:46
throw err
^

Error: read ECONNRESET
at exports._errnoException (util.js:1023:11)
at TLSWrap.onread (net.js:572:26)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "ins
tall"
npm ERR! node v7.5.0
npm ERR! npm v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.4.15 postinstall: node install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\CK\AppData\Roaming\npm-cache_logs\2017-02-13T01_40_23_562Z-debug.log
PS C:\Program Files\nodejs\node_modules\electron>`

* Electron version: Latest on npm
* Node version: v7.5.0
* Operating system: Windows 10

**Comment by apokaliptis** [comment]
I was finally able to get it installed. First I followed the suggestion mentioned above by starting cmd as admin:

`npm -g remove electron`
`del %HomePath%\.electron`
`npm -g cache clear`

Then I navigated to `C:\Program Files\nodejs\node_modules` and manually deleted the Electron folder.

Lastly, I did `npm -g install electron` and it finally worked!

**Comment by eorroe** [comment]
I followed what you did but I still have the same problem

**Comment by Leleking** [comment]
i also have the same problem
