### ISSUE TITLE
[npm / enterprise proxy] Allow download of electron binaries from a custom URL

### ISSUE THREAD

**Issue by JanThiel** [electron-userland/electron-prebuilt#240]
Hi guys,

we are currently facing enterpriseland issues with the electron binaries donwloaded seperately by the npm install package.
We have a strict proxy and firewall in place. npm packages are tunneled via our private repository. Sadly electron doesn't support (or it isn't documented) a way to dowload it's binaries from a custom location. That's why the npm install of electron can never succeed on our servers behind the security layers.

Take a look at phantomJS parameters that solve that issues:

https://www.npmjs.com/package/phantomjs#downloading-from-a-custom-url

Please consider adding such a parameter to electron as well so that users behind proxy and firewall can provide the binary from an internal server.

Thanks alot, best regards,

Jan

**Comment by MarshallOfSound** [comment]
See the README of `electron-download`.

> You can set the ELECTRON_MIRROR or NPM_CONFIG_ELECTRON_MIRROR environment variable or mirror opt variable to use a custom base URL for grabbing Electron zips. The same pattern applies to ELECTRON_CUSTOM_DIR and ELECTRON_CUSTOM_FILENAME:

https://github.com/electron-userland/electron-download

There are environment variables / npm config variables for overriding all aspects of the Electron download URL 👍 You can also configure electron download to use your proxy correctly 👍

**Comment by JanThiel** [comment]
RTFM FTW, thank you :-)
