### ISSUE TITLE
Unable to install Electron with the quick-start tutorial

### ISSUE THREAD

**Issue by cmpsoares91** [electron-userland/electron-prebuilt#242]
If you're having an issue _installing_ Electron, this is the place to report it.
With the quick-start-tutorial I was trying to install electron using both commands:
```
npm install

# and
npm install electron -g

```
However I keep getting the following error:
```
C:\path\to\project\electron-quick-start>npm install electron -g
C:\tools\nodejs\node-v7.9.0-win-x64\electron -> C:\tools\nodejs\node-v7.9.0-win-x64\node_modules\electron\cli.js

> electron@1.6.6 postinstall C:\tools\nodejs\node-v7.9.0-win-x64\node_modules\electron
> node install.js

C:\tools\nodejs\node-v7.9.0-win-x64\node_modules\electron\install.js:47
  throw err
  ^

Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
npm WARN Error: EPERM: operation not permitted, scandir 'C:\tools\nodejs\node-v7.9.0-win-x64\node_modules\electron\node_modules\dashdash\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\tools\nodejs\node-v7.9.0-win-x64\node_modules\electron\node_modules\dashdash\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\tools\\nodejs\\node-v7.9.0-win-x64\\node_modules\\electron\\node_modules\\dashdash\\node_modules' }
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\tools\\nodejs\\node-v7.9.0-win-x64\\node.exe" "C:\\tools\\nodejs\\node-v7.9.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "-g"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\MyUser\AppData\Roaming\npm-cache\_logs\2017-04-28T18_41_12_022Z-debug.log
```

I added the log file as an attachment (did some anonymization to it).

-----

[2017-04-28T18_41_12_022Z-debug.txt](https://github.com/electron-userland/electron-prebuilt/files/965290/2017-04-28T18_41_12_022Z-debug.txt)

* Electron version: "electron": "~1.6.2"
* Operating system: Windows 7 Enterprise SP1

**Comment by hemant1612** [comment]
Hey I am also facing the same issue .
Operating system : Windows 10.



> electron@1.6.6 postinstall C:\Users\HP\AppData\Roaming\npm\node_modules\electron
> node install.js

C:\Users\HP\AppData\Roaming\npm\node_modules\electron\install.js:47
  throw err
  ^

Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2017-04-29T19_50_13_513Z-debug.log

C:\Users\HP\nppm\electron>node install.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\HP\nppm\electron\install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

C:\Users\HP\nppm\electron>node -i install.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\HP\nppm\electron\install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

C:\Users\HP\nppm\electron>node install install.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\HP\nppm\electron\install'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

C:\Users\HP\nppm\electron>npm install -g electron
C:\Users\HP\AppData\Roaming\npm\electron -> C:\Users\HP\AppData\Roaming\npm\node_modules\electron\cli.js

> electron@1.6.6 postinstall C:\Users\HP\AppData\Roaming\npm\node_modules\electron
> node install.js

C:\Users\HP\AppData\Roaming\npm\node_modules\electron\install.js:47
  throw err
  ^

Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\HP\AppData\Roaming\npm\node_modules\electron\node_modules\mkdirp\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\HP\AppData\Roaming\npm\node_modules\electron\node_modules\mkdirp\node_modules'
npm WARN     at Error (native)
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\electron\\node_modules\\mkdirp\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2017-04-29T19_53_33_894Z-debug.log

C:\Users\HP\nppm\electron>

**Comment by furkansa** [comment]
I have the same problem.
Windows 10 x64 creators update
node -v 6.10.2
npm -v 4.5.0
Errno: 4048

**Comment by geekgonecrazy** [comment]
Getting this also on Ubuntu 17.04 worked yesterday afternoon.  But for some reason today i'm getting this error.

**Comment by geekgonecrazy** [comment]
and just suddenly started working.  Weird.  Disregard mine :)

**Comment by malept** [comment]
I locked conversation because the linked issue has a workaround, and the root cause has been reported upstream.

**Comment by malept** [comment]
`extract-zip` 1.6.5 has been released, I've verified that if you update that dependency (or wipe out `node_modules` and reinstall dependencies), you should be able to install the `electron` module again.
