### ISSUE TITLE
Electron not installing (Windows 10)

### ISSUE THREAD

**Issue by Maattah** [electron-userland/electron-prebuilt#246]
This is triggering me so hard, I keep trying to install electron and it just wont.

Error:
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Matth\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "--save-dev" "--verbose"
npm verb node v7.4.0
npm verb npm  v4.5.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.6 postinstall: 'node install.js'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matth\AppData\Roaming\npm-cache\_logs\2017-05-01T01_59_49_850Z-debug.log

Log: [2017-05-01T01_59_49_850Z-debug.txt](https://github.com/electron-userland/electron-prebuilt/files/967186/2017-05-01T01_59_49_850Z-debug.txt)

I have tried running different commands to install it, tried clearing the cache, deleted the downloaded files so they could be re-gotten, messed around with my package.json and it just won't install.

* Electron version: 1.6.6
* Operating system: Windows 10 Home (64-bit)

**Comment by kddlb** [comment]
I'm having the same issue, with both Electron 1.6.6 and 1.6.7, in Windows 10 Pro, 64-bit.

Log: [2017-05-01T02_02_54_823Z-debug.zip](https://github.com/electron-userland/electron-prebuilt/files/967191/2017-05-01T02_02_54_823Z-debug.zip)

**Comment by MarshallOfSound** [comment]
Hey guys, please check out this issue https://github.com/electron-userland/electron-prebuilt/issues/242

(Good idea to look for similar issues before spinning up new ones)

Hopefully this will be sorted out soon 👍
