### ISSUE TITLE
Got stuck after npm install -g

### ISSUE THREAD

**Issue by awguo** [electron-userland/electron-prebuilt#250]
update:

After upgrading npm to latest version, it's still not working but the issue is like this:

> bogon:node_modules awguo$ sudo npm install -g electron
> /usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js
> 
> > electron@1.6.7 postinstall /usr/local/lib/node_modules/electron
> > node install.js
> 
> /usr/local/lib/node_modules/electron/install.js:47
>   throw err
>   ^
> 
> Error: connect ETIMEDOUT 52.216.65.152:443
>     at Object.exports._errnoException (util.js:1022:11)
>     at exports._exceptionWithHostPort (util.js:1045:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! electron@1.6.7 postinstall: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the electron@1.6.7 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/awguo/.npm/_logs/2017-05-11T13_08_22_043Z-debug.log
> 
> 
> 

Installation failed. It seems the server "54.231.82.10:443" is not reachable. Any solution for this?

Thanks,

Here below is the output:

> bogon:node_modules awguo$ sudo npm install -g electron
> /usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js
> 
> electron@1.6.7 postinstall /usr/local/lib/node_modules/electron
> node install.js
> 
> /usr/local/lib/node_modules/electron/install.js:47
>   throw err
>   ^
> 
> Error: connect ETIMEDOUT 54.231.82.10:443
>     at Object.exports._errnoException (util.js:1022:11)
>     at exports._exceptionWithHostPort (util.js:1045:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
> npm ERR! Darwin 16.5.0
> npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "electron"
> npm ERR! node v7.2.1
> npm ERR! npm  v3.10.9
> npm ERR! code ELIFECYCLE
> 
> npm ERR! electron@1.6.7 postinstall: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the electron@1.6.7 postinstall script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the electron package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs electron
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls electron
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /usr/local/lib/node_modules/npm-debug.log

**Comment by zeke** [comment]
See https://github.com/electron/electron/blob/master/docs/faq.md#why-am-i-having-trouble-installing-electron
