### ISSUE TITLE
npm install hangs

### ISSUE THREAD

**Issue by Fandekasp** [electron-userland/electron-prebuilt#256]
* Electron version: None
* Operating system: Arch Linux

Running `$ npm install electron` will hang indefinitely on `> node install.js` without showing any progress. Confirmed after checking the node_modules files size & process activity.

Related: https://github.com/facebook/react-devtools/issues/741

**Comment by Fandekasp** [comment]
Installing electron with pacman worked. The problem might have been due to the installer not being able to symlink the executable to /usr/bin because the file already existed..

**Comment by johnnykoo84** [comment]
Hello @Fandekasp I get the same hang here with @1.6.11 
Did you figure out how to solve this issue?

**Comment by Fandekasp** [comment]
well, the solution was ... not using electron :/ My project got cancelled and I'm not doing react native atm, so I'll unsubscribe myself from this issue
