### ISSUE TITLE
node (vs. nodejs) is required when installing electron

### ISSUE THREAD

**Issue by uri247** [electron-userland/electron-prebuilt#270]
If you're having an issue _installing_ Electron, this is the place to report it.

If you're having an issue _using_ Electron, please report it at https://github.com/electron/electron/issues

* Electron version: 1.6.11
* Operating system: Ubuntu 17.04

Trying to install electron with out nodejs-legacy, yields an error (node not found).

$ sudo npm install -g electron

After installing nodejs-legacy, installation succeeded.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW this behavior is expected, `npm` relies on `node` so it won't work without it

**Comment by uri247** [comment]
I suspect I'm misunderstood about the essence of this issue. **This is not a question or a support issue**. It is definitely a feature request, arguably a bug.

- Node *is* installed on my machine.
- On Debian and Ubuntu distribution, the node executable name is nodejs. See issue #4772 on NodeJS database (https://github.com/nodejs/node-v0.x-archive/issues/4772). 
- I had no problem workaround the issue. The canonical work around is to create a symbolic link from node to nodejs - and this way supporting packages that have 'node' hard coded, including electron.
- I seriously suggest you reopen this issue. Most packages support it. Ubuntu is not a small distribution.

**Comment by MarshallOfSound** [comment]
@uri247 I'll cc some people on this to discuss but as far as I am aware the `nodejs` package on linux is legacy and unsupported.  The version it installs `0.10` / `0.12` is actually end of life according to node's [LTS schedule](https://github.com/nodejs/LTS#lts-schedule1).  And all common node install techniques for linux (that aren't this legacy package) install the correct executable (`node`).

I am of the opinion that this is an issue with how node was installed in the legacy package and not an issue with electron calling `node install.js`.

What do you think @malept ?

**Comment by malept** [comment]
Ubuntu 17.04 installs Node 4.x (has been since at least 16.04). That being said, it's really odd that `nodejs-legacy` exists (the package that provides the `nodejs` :arrow_right: `node` symlink), from a Node ecosystem point of view. _(It makes slightly more sense from a Debian packaging POV...)_

My opinion is that we should add to the docs "requires nodejs-legacy installed when using the system Node packages on Debian/Ubuntu."

**Comment by MarshallOfSound** [comment]
> My opinion is that we should add to the docs "requires nodejs-legacy installed when using the system Node packages on Debian/Ubuntu."

Sounds good to me 👍
