### ISSUE TITLE
Can't install in Windows10

### ISSUE THREAD

**Issue by kimpa0107** [electron-userland/electron-prebuilt#271]
If you're having an issue _installing_ Electron, this is the place to report it.

If you're having an issue _using_ Electron, please report it at https://github.com/electron/electron/issues

* Electron version: 1.4.15
* Operating system: Windows 10

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nodejieba@2.2.5 (node_modules\nodejieba):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nodejieba@2.2.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\project\electronic-wechat\npm-debug.log

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron/blob/master/docs/faq.md#why-am-i-having-trouble-installing-electron
