### ISSUE TITLE
Change electron binary path via environment variable?

### ISSUE THREAD

**Issue by alexstrat** [electron-userland/electron-prebuilt#274]
How do you test a locally built version of Electron inside an existing Electron application using `electron-prebuilt`?

I suggest being able to change the binary path via an environment variable:
```bash
# will use the installed prebuilt binary
$ electron .
# will use the locally built binary
$ ELECTRON_BINARY_PATH="~/me/electron/out/D/Electron.app/Contents/MacOS/Electron" electron .
```

**Comment by MarshallOfSound** [comment]
I have a script to copy paste the output from the `electron` repo into the `dist` folder in a locally installed prebuilt module 😆 

That said, this PR https://github.com/electron/electron/pull/10172 should allow us to just run `npm link` from the `electron` repo 😄

**Comment by alexstrat** [comment]
electron/electron#10172 + `npm link` is the way to go :)
