### ISSUE TITLE
Partially downloaded electron package fails to install and install electron-prebuilt will not redownload

### ISSUE THREAD

**Issue by dekarguy** [electron-userland/electron-prebuilt#51]
I just had a hiccup in my internet while installing electron-prebuilt 0.30.4 and ended up with a 9.5 MB download of the zip for it instead of the 45.4 MB version. The install failed of course, and upon repeat attempts to install, it always got the same error and never attempted to re-download the zip.

Deleting the cached version from my user/.electron folder ended up making it download again and install correctly.

Perhaps a file size check of md5 verification on the cache after detecting that the file exists would be helpful.

Here is the error for reference:

Downloading electron-v0.30.4-win32-x64.zip
Error: GET https://github.com/atom/electron/releases/download/v0.30.4/electron-v0.30.4-win32-x64.zip returned 503

**Comment by maxogden** [comment]
@dekarguy sorry about that. we should definitely improve this

**Comment by malept** [comment]
See also: https://github.com/electron-userland/electron-download/issues/19
