### ISSUE TITLE
Using ia32 version on x64 windows system

### ISSUE THREAD

**Issue by olegam** [electron-userland/electron-prebuilt#53]
The ia32 windows build seems to work fine on x64 systems but not vice versa. I would prefer to only distribute one windows version (32 bit) of my app, but still build it on a x64 system. Is there any way to install the ia32 version on x64 windows (besides from copying the folder from another system)?

And is this recommended at all? Should I rather just distribute separate ia32 and x64 windows versions of my app?

**Comment by olegam** [comment]
Seems electron-downloader supports an `arch` option that will override the value of `os.arch()` so if that parameter could be passed somehow then it should be possible to install the module for another architecture I guess?

**Comment by etiktin** [comment]
In the mean time, while the PR is in the works, you can force using ia32, by installing and using the 32 bit version of node, since `os.arch()` returns the architecture of node and not the OS (this is true at least for Windows).

**Comment by kevinsawicki** [comment]
I believe this was addressed by https://github.com/electron-userland/electron-prebuilt/pull/60 and so this issue cannot be closed.

**Comment by englishextra** [comment]
>>Should I rather just distribute separate ia32 and x64 windows versions of my app?
Yes.
