### ISSUE TITLE
npm install error: Cannot find module 'process-nextick-args' / Installing wrong version

### ISSUE THREAD

**Issue by stevenmwade** [electron-userland/electron-prebuilt#63]
Reinstalling electon-prebuilt because npm wouldn't update it and the reinstall came with this nifty error:
Cannot find module 'process-nextick-args'

It seems like it is not installing any of it's own modules. It also isn't installing the latest version on another computer, only version 0.25.3.

**Comment by maxogden** [comment]
What version of node are you using, and what operating system version are you on?

**Comment by stevenmwade** [comment]
v.0.12.7 and OSX

**Comment by ngoldman** [comment]
@stevenmwade can you please try using a more recent version of node?

A similar issue was resolved in #46 by upgrading node. I recommend version 4 as it's the current stable long term support version.

**Comment by kevinsawicki** [comment]
Closing this out since it should be resolved by upgrading node, please comment if you are still experiencing it with node 4 or above.

**Comment by kevinsawicki** [comment]
Opening this back up after seeing https://github.com/electron-userland/electron-prebuilt/issues/121 which reports something similar on node 6.

What version of npm are you using? There seems to be several reports of this on other projects as well:

https://github.com/sass/node-sass/issues/1268
https://github.com/angular/angular-cli/issues/1930

**Comment by zeke** [comment]
Looking through the above-mentioned issues, it appears that this was an npm bug and the solution is to update to a recent version of node 4 or node 6. Gonna close this out, but @stevenmwade feel free to comment on this issue if you're still having problems.
