### ISSUE TITLE
Download of electron-prebuilt node module

### ISSUE THREAD

**Issue by naveen50003** [electron-userland/electron-prebuilt#66]
I am getting Error While downloading electron-prebuilt node module in my local System.In this attachment i kept Screenshot to show errors which are coming while i am downloading this node module.Please resolve my issue
![npm_error](https://cloud.githubusercontent.com/assets/14138109/10676992/6427a772-7927-11e5-9420-3a3d5f2f1cc3.png)

**Comment by mafintosh** [comment]
Do you consistently get this error? This looks like a network issue

**Comment by smileboywtu** [comment]
got this error too, why not use the url of the the electron mirror list?

``` shell
Error: connect ETIMEDOUT 54.231.12.177:443

```

**Comment by smileboywtu** [comment]
after several hours work, I just find out how to fix this error:
<hr>

use the different electron mirror, in fish shell just set the npm install mirror:

for example, china:

set -x NPM_CONFIG_ELECTRON_MIRROR "https://npm.taobao.org/mirrors/electron/"

then cd to the electron-prebuilt dir and exec:

node install.js

**Comment by liaoaoyang** [comment]
@smileboywtu it works for me!

thx u!

**Comment by smileboywtu** [comment]
wow, hope you'll like it.

**Comment by ngoldman** [comment]
Marking this as resolved since it seems to be network related, so not related to `electron-prebuilt`.
