### ISSUE TITLE
latest version on npm does not match latest version on github

### ISSUE THREAD

**Issue by kevin-smets** [electron-userland/electron-prebuilt#71]
At the time of writing, npm should list v0.35.1 as latest version. However, on https://www.npmjs.com/package/electron-prebuilt, it lists 0.34.4 as latest release.

<img width="358" alt="screen shot 2015-11-27 at 05 53 20" src="https://cloud.githubusercontent.com/assets/4222494/11434349/736d2990-94cb-11e5-8bdc-335b2b7d7dd5.png">

For some reason, `npm i -D electron-prebuilt` works just dandy, it installs v0.35.1 and saved the proper tag in my package.json. 

But running `npm info electron-prebuilt` returns nothing at all. This causes problems for other modules like npm-check-updates...

**Comment by johnmuhl** [comment]
Yes this happens when Electron publishes new versions of old releases. I [tried to solve it][1] once before but apparently that doesn't work. If anyone is has ideas for what to try next I'm all :ear:s

[1]: https://github.com/johnmuhl/electron-prebuilt-updater/commit/38354f4cb48d166070fbc5588ddb759971f5d71a

**Comment by zeke** [comment]
This is an issue with npm's website. The ideal thing would be for npm to provide a way to view a list of all versions on the site, but alas no such feature exists. Also their website is not open source any more, so you can't submit a PR to improve the state of things. The best you can do is open an issue at https://github.com/npm/www/issues

In the meantime, you can always see a full list of versions for any package with this command:

```sh
npm show electron-prebuilt versions
```
