### ISSUE TITLE
fails install on windows

### ISSUE THREAD

**Issue by PGA68** [electron-userland/electron-prebuilt#96]
**I do next:**
git clone https://github.com/atom/electron-quick-start
cd electron-quick-start
npm install

**My versions equipment is:**
{ 'electron-quick-start': '1.0.0',
  npm: '3.7.5',
  ares: '1.10.1-DEV',
  http_parser: '2.6.2',
  icu: '56.1',
  modules: '47',
  node: '5.7.0',
  openssl: '1.0.2f',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

**I have result:**
> node install.js
### C:\Users\User\home\atom-electron\electron-quick-start\node_modules\electron-prebuilt\install.js:22
  throw err
  ^
Error: end of central directory record signature not found
    at C:\Users\User\home\atom-electron\electron-quick-start\node_modules\yauzl\index.js:167:14
    at C:\Users\User\home\atom-electron\electron-quick-start\node_modules\yauzl\index.js:473:5
    at C:\Users\User\home\atom-electron\electron-quick-start\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! electron-prebuilt@0.36.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.9 postinstall script 'node install.js'.

**Comment by maxogden** [comment]
`end of central directory record signature not found` usually means somehow the zip file download is corrupted or incomplete, can you try deleting `C:\Users\User\home\atom-electron\electron-quick-start\node_modules\` and try again? If that doesn't work, look for a folder called `.electron` in your users home folder and try deleting that and then trying again.

**Comment by MathijsvVelde** [comment]
I have:
- a different app
- the same error
- and the same error after deleting the `node_modules` folder and installing it again

**Comment by kevinsawicki** [comment]
I believe this is addressed by new versions (1.4.1+) doing checksum comparisons introduced in #189 that verifies the downloaded `.zip` is not corrupt, closing out.
